folio-org/ui-quick-marc

- .eslintrc
- .gitignore
- CHANGELOG.md
- CONTRIBUTING.md
- Jenkinsfile
- LICENSE
- PULL_REQUEST_TEMPLATE.md
- README.md
- index.js
- jest.config.js
- package.json
- src/QuickMarc.js
- src/index.js
- test/bigtest/.eslintrc
- test/bigtest/helpers/PluginHarness.js
- test/bigtest/helpers/setup-application.js
- test/bigtest/index.js
- test/bigtest/interactors/PluginInteractor.js
- test/bigtest/interactors/index.js
- test/bigtest/network/boot.js
- test/bigtest/network/config.js
- test/bigtest/network/index.js
- test/bigtest/network/scenarios/default.js
- test/bigtest/tests/plugin-test.js
- translations/ui-quick-marc/en.json
https://issues.folio.org/browse/UIQM-10 …
> UIQM-10 Project Setup: ui-quick-marc

- package.json
https://issues.folio.org/browse/UIQM-10 …
> UIQM-10 stripes-acq-dep

- translations/ui-quick-marc/ar.json
- translations/ui-quick-marc/ca.json
- translations/ui-quick-marc/da.json
- translations/ui-quick-marc/de.json
- translations/ui-quick-marc/en_GB.json
- translations/ui-quick-marc/en_SE.json
- translations/ui-quick-marc/en_US.json
- translations/ui-quick-marc/es.json
- translations/ui-quick-marc/es_419.json
- translations/ui-quick-marc/es_ES.json
- translations/ui-quick-marc/fr.json
- translations/ui-quick-marc/fr_FR.json
- translations/ui-quick-marc/he.json
- translations/ui-quick-marc/hu.json
- translations/ui-quick-marc/it_IT.json
- translations/ui-quick-marc/ja.json
- translations/ui-quick-marc/pt_BR.json
- translations/ui-quick-marc/pt_PT.json
- translations/ui-quick-marc/ru.json
- translations/ui-quick-marc/ur.json
- translations/ui-quick-marc/zh_CN.json
- translations/ui-quick-marc/zh_TW.json
> Update translation strings as of 20200316T134017

- translations/ui-quick-marc/ar.json
- translations/ui-quick-marc/pt_BR.json
> Update translation strings as of 20200317T123814

- README.md
Use initial year of creation in README
In subsequent years, use range of years.
> FOLIO-360 Use initial year of creation in README

- package.json
- src/QuickMarc.js
- test/bigtest/tests/noPermissions/QuickMarc-test.js
https://issues.folio.org/browse/UIQM-9 …
> UIQM-9 quickMARC permissions

- CHANGELOG.md
https://issues.folio.org/browse/UIQM-9 …
> UIQM-9 Add change log

- package.json
- src/QuickMarc.js
https://issues.folio.org/browse/UIQM-9 …
> UIQM-9 fix permission name

- package.json
> UIQM-9 change permission name

- src/QuickMarcEditor/QuickMarcEditorRows/FixedField/ScoreFixedField.js
https://issues.folio.org/browse/UIQM-3 …
> UIQM-4 fix LTxt field

- CHANGELOG.md
- src/QuickMarcEditor/QuickMarcEditorContainer.js
- src/QuickMarcEditor/QuickMarcEditorContainer.test.js
- src/QuickMarcEditor/utils.js
- src/QuickMarcEditor/utils.test.js
- test/bigtest/network/configs/configMarcRecords.js
- test/bigtest/network/factories/marcRecord.js
- test/bigtest/tests/QuickMarcEditor-test.js
https://issues.folio.org/browse/UIQM-3 …
> UIQM-3 fix request query

- src/QuickMarcEditor/QuickMarcEditorContainer.js
- src/QuickMarcEditor/QuickMarcEditorRows/utils.js
- src/QuickMarcEditor/QuickMarcEditorRows/utils.test.js
- src/QuickMarcEditor/utils.js
- src/QuickMarcEditor/utils.test.js
- test/bigtest/tests/QuickMarcEditor-permissions-test.js
- translations/ui-quick-marc/en.json
https://issues.folio.org/browse/UIQM-7 …
> UIQM-7 UI check when saving an edited record in quickMARC

- package.json
- src/QuickMarcEditor/QuickMarcEditor.js
- src/QuickMarcEditor/QuickMarcEditorContainer.js
- src/QuickMarcEditor/QuickMarcEditorRows/QuickMarcEditorRows.js
- src/QuickMarcEditor/QuickMarcEditorRows/utils.js
- src/QuickMarcEditor/QuickMarcEditorRows/utils.test.js
https://issues.folio.org/browse/UIQM-3 …
> UIQM-3 leader content should be editable

- CHANGELOG.md
- src/QuickMarcEditor/utils.js
- src/QuickMarcEditor/utils.test.js
- translations/ui-quick-marc/en.json
https://issues.folio.org/browse/UIQM-13 …
> UIQM-13 UI check for record type when saving an edited record in quickMARC

- src/QuickMarcEditor/QuickMarcEditorRows/utils.js
https://issues.folio.org/browse/UIQM-6 …
> UIQM-6 Add 003 field to delete exception rows

- translations/ui-quick-marc/fr_FR.json
- translations/ui-quick-marc/pt_BR.json
> Update translation strings as of 20200409T134057

- CHANGELOG.md
- src/QuickMarcEditor/QuickMarcEditorContainer.js
- src/QuickMarcEditor/QuickMarcEditorContainer.test.js
- src/QuickMarcEditor/utils.js
- src/QuickMarcEditor/utils.test.js
- test/bigtest/helpers/PluginHarness.js
- test/bigtest/interactors/QuickMarcEditorInteractor.js
- test/bigtest/network/configs/configMarcRecords.js
- test/bigtest/network/factories/marcRecord.js
- test/bigtest/tests/QuickMarcEditor-test.js
- translations/ui-quick-marc/en.json
https://issues.folio.org/browse/UIQM-8 …
> UIQM-8 Save edited record in quickMARC to SRS

- src/QuickMarcEditor/QuickMarcEditor.js
- src/QuickMarcEditor/QuickMarcEditorContainer.js
https://issues.folio.org/browse/UIQM-8 …
> UIQM-8 save with shortcut

- translations/ui-quick-marc/ja.json
> Update translation strings as of 20200415T223222

- CHANGELOG.md
- package.json
- src/QuickMarcEditor/QuickMarcEditor.js
- translations/ui-quick-marc/en.json
https://issues.folio.org/browse/UIQM-15 …
> UIQM-15 Add permission translation

- translations/ui-quick-marc/ar.json
- translations/ui-quick-marc/ca.json
- translations/ui-quick-marc/da.json
- translations/ui-quick-marc/de.json
- translations/ui-quick-marc/en_GB.json
- translations/ui-quick-marc/en_SE.json
- translations/ui-quick-marc/en_US.json
- translations/ui-quick-marc/es.json
- translations/ui-quick-marc/es_419.json
- translations/ui-quick-marc/es_ES.json
- translations/ui-quick-marc/fr.json
- translations/ui-quick-marc/fr_FR.json
- translations/ui-quick-marc/he.json
- translations/ui-quick-marc/hu.json
- translations/ui-quick-marc/it_IT.json
- translations/ui-quick-marc/ja.json
- translations/ui-quick-marc/pt_BR.json
- translations/ui-quick-marc/pt_PT.json
- translations/ui-quick-marc/ru.json
- translations/ui-quick-marc/ur.json
- translations/ui-quick-marc/zh_CN.json
- translations/ui-quick-marc/zh_TW.json
> Update translation strings as of 20200420T134821

- translations/ui-quick-marc/ar.json
- translations/ui-quick-marc/ja.json
- translations/ui-quick-marc/pt_BR.json
> Update translation strings as of 20200421T180634

- CHANGELOG.md
- src/QuickMarcEditor/QuickMarcEditorRows/FixedField/FixedField.js
- src/QuickMarcEditor/QuickMarcEditorRows/QuickMarcEditorRows.js
- test/bigtest/tests/QuickMarcEditor-test.js
- translations/ui-quick-marc/en.json
https://issues.folio.org/browse/UIQM-16 …
> UIQM-16 Edit quickMarc accessibility

- translations/ui-quick-marc/ar.json
> Update translation strings as of 20200424T193712

- translations/ui-quick-marc/fr_FR.json
> Update translation strings as of 20200428T150732

- CHANGELOG.md
- package.json
- src/QuickMarcEditor/QuickMarcEditor.js
- src/QuickMarcEditor/QuickMarcEditorRows/FixedField/FixedField.css
- src/QuickMarcEditor/QuickMarcEditorRows/FixedField/FixedField.js
- src/QuickMarcEditor/QuickMarcEditorRows/QuickMarcEditorRows.css
- src/QuickMarcEditor/QuickMarcEditorRows/QuickMarcEditorRows.js
https://issues.folio.org/browse/UIQM-18 …
> UIQM-18 Reduce margins and white space in quickMARC

- CHANGELOG.md
- src/QuickMarcEditor/QuickMarcEditorRows/QuickMarcEditorRows.js
- translations/ui-quick-marc/en.json
https://issues.folio.org/browse/UIQM-20 …
> UIQM-20 Update modal label and message for delete field

- CHANGELOG.md
- src/QuickMarcEditor/utils.js
- src/QuickMarcEditor/utils.test.js
- test/bigtest/tests/QuickMarcEditor-test.js
- translations/ui-quick-marc/en.json
https://issues.folio.org/browse/UIQM-21 …
> UIQM-21 UI check for Leader when saving a record in quickMARC

- CHANGELOG.md
- package.json
https://issues.folio.org/browse/UIQM-27 …
> UIQM-27 ui-quick-marc app: Update to Stripes v4

- translations/ui-quick-marc/ar.json
- translations/ui-quick-marc/ca.json
- translations/ui-quick-marc/da.json
- translations/ui-quick-marc/de.json
- translations/ui-quick-marc/en_GB.json
- translations/ui-quick-marc/en_SE.json
- translations/ui-quick-marc/en_US.json
- translations/ui-quick-marc/es.json
- translations/ui-quick-marc/es_419.json
- translations/ui-quick-marc/es_ES.json
- translations/ui-quick-marc/fr.json
- translations/ui-quick-marc/fr_FR.json
- translations/ui-quick-marc/he.json
- translations/ui-quick-marc/hu.json
- translations/ui-quick-marc/it_IT.json
- translations/ui-quick-marc/ja.json
- translations/ui-quick-marc/pt_BR.json
- translations/ui-quick-marc/pt_PT.json
- translations/ui-quick-marc/ru.json
- translations/ui-quick-marc/ur.json
- translations/ui-quick-marc/zh_CN.json
- translations/ui-quick-marc/zh_TW.json
> Update translation strings as of 20200513T135229

- translations/ui-quick-marc/ar.json
- translations/ui-quick-marc/ca.json
- translations/ui-quick-marc/da.json
- translations/ui-quick-marc/de.json
- translations/ui-quick-marc/en_GB.json
- translations/ui-quick-marc/en_SE.json
- translations/ui-quick-marc/en_US.json
- translations/ui-quick-marc/es.json
- translations/ui-quick-marc/es_419.json
- translations/ui-quick-marc/es_ES.json
- translations/ui-quick-marc/fr.json
- translations/ui-quick-marc/fr_FR.json
- translations/ui-quick-marc/he.json
- translations/ui-quick-marc/hu.json
- translations/ui-quick-marc/it_IT.json
- translations/ui-quick-marc/ja.json
- translations/ui-quick-marc/pt_BR.json
- translations/ui-quick-marc/pt_PT.json
- translations/ui-quick-marc/ru.json
- translations/ui-quick-marc/ur.json
- translations/ui-quick-marc/zh_CN.json
- translations/ui-quick-marc/zh_TW.json
> Update translation strings as of 20200515T182823

- CHANGELOG.md
- src/QuickMarcEditor/QuickMarcEditorRows/ContentField/ContentField.js
- src/QuickMarcEditor/QuickMarcEditorRows/ContentField/ContentField.test.js
- src/QuickMarcEditor/QuickMarcEditorRows/ContentField/index.js
- src/QuickMarcEditor/QuickMarcEditorRows/ContentField/utils.js
- src/QuickMarcEditor/QuickMarcEditorRows/ContentField/utils.test.js
- src/QuickMarcEditor/QuickMarcEditorRows/QuickMarcEditorRows.js
- test/bigtest/tests/QuickMarcEditor-test.js
https://issues.folio.org/browse/UIQM-26 …
> UIQM-26 Wrap text in quickMARC

- translations/ui-quick-marc/fr_FR.json
- translations/ui-quick-marc/pt_BR.json
- translations/ui-quick-marc/ru.json
> Update translation strings as of 20200519T123842

- src/QuickMarcEditor/utils.js
- src/QuickMarcEditor/utils.test.js
- translations/ui-quick-marc/en.json
https://issues.folio.org/browse/UIQM-24 …
> UIQM-24 UI check for field character and Leader length in quickMARC

- src/QuickMarcEditor/utils.js
> UIQM-14 Add empty indicators

- translations/ui-quick-marc/ar.json
- translations/ui-quick-marc/ca.json
- translations/ui-quick-marc/da.json
- translations/ui-quick-marc/de.json
- translations/ui-quick-marc/en_GB.json
- translations/ui-quick-marc/en_SE.json
- translations/ui-quick-marc/en_US.json
- translations/ui-quick-marc/es.json
- translations/ui-quick-marc/es_419.json
- translations/ui-quick-marc/es_ES.json
- translations/ui-quick-marc/fr.json
- translations/ui-quick-marc/fr_FR.json
- translations/ui-quick-marc/he.json
- translations/ui-quick-marc/hu.json
- translations/ui-quick-marc/it_IT.json
- translations/ui-quick-marc/ja.json
- translations/ui-quick-marc/pt_BR.json
- translations/ui-quick-marc/pt_PT.json
- translations/ui-quick-marc/ru.json
- translations/ui-quick-marc/ur.json
- translations/ui-quick-marc/zh_CN.json
- translations/ui-quick-marc/zh_TW.json
> Update translation strings as of 20200526T141248

- translations/ui-quick-marc/fr_FR.json
- translations/ui-quick-marc/pt_BR.json
- translations/ui-quick-marc/ru.json
> Update translation strings as of 20200527T144757

- CHANGELOG.md
- src/QuickMarcEditor/QuickMarcEditorRows/BytesField/BytesField.css
- src/QuickMarcEditor/QuickMarcEditorRows/IndicatorField/IndicatorField.js
- src/QuickMarcEditor/QuickMarcEditorRows/QuickMarcEditorRows.css
- src/QuickMarcEditor/QuickMarcEditorRows/QuickMarcEditorRows.js
- src/QuickMarcEditor/utils.js
- src/QuickMarcEditor/utils.test.js
- test/bigtest/tests/QuickMarcEditor-test.js
- translations/ui-quick-marc/en.json
https://issues.folio.org/browse/UIQM-33 …
> UIQM-33 UI check for Leader and 008 in quickMARC

- src/QuickMarcEditor/QuickMarcEditorRows/BytesField/BytesField.js
- src/QuickMarcEditor/QuickMarcEditorRows/FixedField/VisualMaterialFixedField.js
https://issues.folio.org/browse/UIQM-4 …
> UIQM-4 missed field

- CHANGELOG.md
- src/QuickMarcEditor/QuickMarcEditor.js
- src/QuickMarcEditor/QuickMarcEditorContainer.js
- translations/ui-quick-marc/en.json
https://issues.folio.org/browse/UIQM-34 …
> UIQM-34 Error when opening quickMARC

- src/QuickMarcEditor/QuickMarcEditor.js
- src/QuickMarcEditor/QuickMarcEditorRows/FixedField/FixedFieldFactory.js
- src/QuickMarcEditor/QuickMarcEditorRows/FixedField/FixedFieldFactory.test.js
- src/QuickMarcEditor/QuickMarcEditorRows/MaterialCharsField/MaterialCharsFieldFactory.js
- src/QuickMarcEditor/QuickMarcEditorRows/MaterialCharsField/MaterialCharsFieldFactory.test.js
- src/QuickMarcEditor/QuickMarcEditorRows/QuickMarcEditorRows.js
https://issues.folio.org/browse/UIQM-4 …
> UIQM-4 fix field type definition

- src/QuickMarcEditor/utils.js
- src/QuickMarcEditor/utils.test.js
https://issues.folio.org/browse/UIQM-5 …
> UIQM-5 fix fields reordering

- CHANGELOG.md
- src/QuickMarcEditor/QuickMarcEditorRows/MaterialCharsField/VisualMaterialCharsField.js
- translations/ui-quick-marc/en.json
https://issues.folio.org/browse/UIQM-37 …
> UIQM-37 Byte errors in 006 and 007

- CHANGELOG.md
- package.json
- src/QuickMarcEditor/QuickMarcEditorRows/PhysDescriptionField/PicturePhysDescriptionField.js
https://issues.folio.org/browse/UIQM-38 …
> UIQM-38 Missing byte in 007

- CHANGELOG.md
- src/QuickMarcEditor/QuickMarcEditorContainer.js
- translations/ui-quick-marc/en.json
https://issues.folio.org/browse/UIQM-39 …
> UIQM-39 Save message for Change Manager queue

- translations/ui-quick-marc/ar.json
- translations/ui-quick-marc/ca.json
- translations/ui-quick-marc/da.json
- translations/ui-quick-marc/de.json
- translations/ui-quick-marc/en_GB.json
- translations/ui-quick-marc/en_SE.json
- translations/ui-quick-marc/en_US.json
- translations/ui-quick-marc/es.json
- translations/ui-quick-marc/es_419.json
- translations/ui-quick-marc/es_ES.json
- translations/ui-quick-marc/fr.json
- translations/ui-quick-marc/fr_FR.json
- translations/ui-quick-marc/he.json
- translations/ui-quick-marc/hu.json
- translations/ui-quick-marc/it_IT.json
- translations/ui-quick-marc/ja.json
- translations/ui-quick-marc/pt_BR.json
- translations/ui-quick-marc/pt_PT.json
- translations/ui-quick-marc/ru.json
- translations/ui-quick-marc/ur.json
- translations/ui-quick-marc/zh_CN.json
- translations/ui-quick-marc/zh_TW.json
> Update translation strings as of 20200608T134746

- translations/ui-quick-marc/ar.json
> Update translation strings as of 20200609T205925

- CHANGELOG.md
- package.json
https://issues.folio.org/browse/UISACQCOMP-3
While it's helpful for reviewers to help …
> UISACQCOMP-3 Handle import of stripes-acq-components to modules and platform

- package.json
> UISACQCOMP-3 Handle import of stripes-acq-components to modules and platform - fix config position

- CHANGELOG.md
- package.json
- src/QuickMarcEditor/QuickMarcEditor.js
- src/QuickMarcEditor/QuickMarcEditor.test.js
- src/QuickMarcEditor/QuickMarcRecordInfo/QuickMarcRecordInfo.css
- src/QuickMarcEditor/QuickMarcRecordInfo/QuickMarcRecordInfo.js
- src/QuickMarcEditor/QuickMarcRecordInfo/QuickMarcRecordInfo.test.js
- src/QuickMarcEditor/QuickMarcRecordInfo/constants.js
- src/QuickMarcEditor/QuickMarcRecordInfo/index.js
- test/bigtest/interactors/QuickMarcEditorInteractor.js
- test/bigtest/tests/QuickMarcEditor-test.js
- translations/ui-quick-marc/en.json
https://issues.folio.org/browse/UIQM-42 …
> UIQM-42 Display quickMARC record's edit status

- translations/ui-quick-marc/ar.json
- translations/ui-quick-marc/ca.json
- translations/ui-quick-marc/da.json
- translations/ui-quick-marc/de.json
- translations/ui-quick-marc/en_GB.json
- translations/ui-quick-marc/en_SE.json
- translations/ui-quick-marc/en_US.json
- translations/ui-quick-marc/es.json
- translations/ui-quick-marc/es_419.json
- translations/ui-quick-marc/es_ES.json
- translations/ui-quick-marc/fr.json
- translations/ui-quick-marc/fr_FR.json
- translations/ui-quick-marc/he.json
- translations/ui-quick-marc/hu.json
- translations/ui-quick-marc/it_IT.json
- translations/ui-quick-marc/ja.json
- translations/ui-quick-marc/pt_BR.json
- translations/ui-quick-marc/pt_PT.json
- translations/ui-quick-marc/ru.json
- translations/ui-quick-marc/ur.json
- translations/ui-quick-marc/zh_CN.json
- translations/ui-quick-marc/zh_TW.json
> Update translation strings as of 20200727T130814

- translations/ui-quick-marc/ru.json
> Update translation strings as of 20200728T221039

- CHANGELOG.md
- package.json
- src/QuickMarcEditor/QuickMarcEditor.js
https://issues.folio.org/browse/UIQM-43 …
> Release v1.1.0

- CHANGELOG.md
- package.json
https://issues.folio.org/browse/UIQM-47 …
> UIQM-47 increment @folio/stripes to v5

- src/QuickMarcEditor/QuickMarcEditorContainer.js
- translations/ui-quick-marc/en.json
https://issues.folio.org/browse/UIQM-48 …
> UIQM-48 quickMARC error message for 006 and 007 character length

- translations/ui-quick-marc/ar.json
- translations/ui-quick-marc/ca.json
- translations/ui-quick-marc/da.json
- translations/ui-quick-marc/de.json
- translations/ui-quick-marc/en_GB.json
- translations/ui-quick-marc/en_SE.json
- translations/ui-quick-marc/en_US.json
- translations/ui-quick-marc/es.json
- translations/ui-quick-marc/es_419.json
- translations/ui-quick-marc/es_ES.json
- translations/ui-quick-marc/fr.json
- translations/ui-quick-marc/fr_FR.json
- translations/ui-quick-marc/he.json
- translations/ui-quick-marc/hu.json
- translations/ui-quick-marc/it_IT.json
- translations/ui-quick-marc/ja.json
- translations/ui-quick-marc/pt_BR.json
- translations/ui-quick-marc/pt_PT.json
- translations/ui-quick-marc/ru.json
- translations/ui-quick-marc/ur.json
- translations/ui-quick-marc/zh_CN.json
- translations/ui-quick-marc/zh_TW.json
> Update translation strings as of 20200820T141724

- CHANGELOG.md
- package.json
https://issues.folio.org/browse/UIQM-49 UIQM (ui-quick-marc) Hotfix release
While it's …
> UIQM-49 UIQM (ui-quick-marc) Hotfix release

- translations/ui-quick-marc/fr_FR.json
- translations/ui-quick-marc/pt_BR.json
- translations/ui-quick-marc/zh_CN.json
> Update translation strings as of 20200824T140725

- translations/ui-quick-marc/zh_CN.json
> Update translation strings as of 20200827T215834

- translations/ui-quick-marc/ar.json
- translations/ui-quick-marc/hi_IN.json
- translations/ui-quick-marc/ko.json
- translations/ui-quick-marc/pl.json
> Update translation strings as of 20200924T211627

- CHANGELOG.md
- src/QuickMarcEditor/QuickMarcRecordInfo/QuickMarcRecordInfo.js
https://issues.folio.org/browse/UIQM-51 …
> UIQM-51 Quick-Marc | Consume {{FormattedDate}} and {{FormattedTime}} via stripes-component

- CHANGELOG.md
- jest.config.js
- package.json
https://issues.folio.org/browse/UIQM-45 …
> Release v2.0.0

- translations/ui-quick-marc/it_IT.json
> Update translation strings as of 20201105T151643

- .eslintrc
- CHANGELOG.md
- package.json
- src/QuickMarcEditor/QuickMarcEditor.js
https://issues.folio.org/browse/UIQM-70
https://issues.folio.org/browse/UIQM-75
While it's …
> UIQM-70 Update stripes to v6.0.0, Update stripes-cli to v2

- CHANGELOG.md
- package.json
- translations/ui-quick-marc/en.json
Added permission to Duplicate MARC bib record
[UIQM-68](https://issues.folio.org/browse/UIQM-68)
> UIQM-68: Permission: Duplicate and create a new MARC bibliographic record

- CHANGELOG.md
- package.json
- translations/ui-quick-marc/en.json
Change permission name FROM quickMARC: View, edit TO quickMARC: View, edit MARC bibliographic record
[UIQM-81](https://issues.folio.org/browse/UIQM-81)
> UIQM-81: Change permission name FROM quickMARC: View, edit TO quickMARC: View, edit MARC bibliographic record

- CHANGELOG.md
- PERSONAL_DATA_DISCLOSURE.md
https://issues.folio.org/browse/UIQM-64 …
> UIQM-64 Add personal data disclosure form

- CHANGELOG.md
- src/QuickMarcEditor/utils.js
- src/QuickMarcEditor/utils.test.js
Do not send fields with empty content to duplicate MARC record
[UIQM-83](https://issues.folio.org/browse/UIQM-83)
> UIQM-83: Could not Derive a new MARC bib record

- src/QuickMarcEditor/QuickMarcDuplicateWrapper.js
- src/QuickMarcEditor/QuickMarcDuplicateWrapper.test.js
- src/QuickMarcEditor/constants.js
> UIQM-82: Fix delay issue

- CHANGELOG.md
- src/QuickMarcEditor/QuickMarcEditor.js
Add shortcuts: 
- Save a record
- Go to Search and Filter pane
Issue: [UIQM-90](https://issues.folio.org/browse/UIQM-90)
Write tests for this functionality. Previous seems test flow used in `ui-eholdings` does not work here. Probably it should be rewrite with `<CommandList>` or find the new way to test it. 
Ideally all of the PRs involved in breaking …
> UIQM-90: Add shortcut keys to save a record and to move on search pane

- CHANGELOG.md
- src/QuickMarcEditor/QuickMarcDuplicateWrapper.js
- src/QuickMarcEditor/QuickMarcDuplicateWrapper.test.js
- src/QuickMarcEditor/QuickMarcEditWrapper.js
- src/QuickMarcEditor/constants.js
- src/QuickMarcEditor/utils.js
- src/QuickMarcEditor/utils.test.js
Auto-populate a subfield section with leading $a when no leading subfield is present
[UIQM-86](https://issues.folio.org/browse/UIQM-86)
> UIQM-86 Auto-populate a subfield section with leading  when no leading subfield is present

- CHANGELOG.md
- Jenkinsfile
- package.json
Issue: [UIQM-92](https://issues.folio.org/browse/UIQM-92)
While it's helpful for reviewers …
> UIQM-92: Compile translation files into AST format

- src/QuickMarcEditor/QuickMarcRecordInfo/QuickMarcRecordInfo.js
> UIQM-94: Fix translation

- CHANGELOG.md
- src/QuickMarcEditor/QuickMarcEditor.js
- translations/ui-quick-marc/en.json
Update Delete field(s) modal's Cancel button label
[UIQM-96](https://issues.folio.org/browse/UIQM-96)
> UIQM-96: Update Delete field(s) modal's Cancel button label

- CHANGELOG.md
- src/QuickMarcEditor/QuickMarcDuplicateWrapper.js
- src/QuickMarcEditor/QuickMarcEditWrapper.js
- src/QuickMarcEditor/QuickMarcEditor.js
- src/QuickMarcEditor/QuickMarcEditorRows/MaterialCharsField/BookMaterialCharsField.js
- src/QuickMarcEditor/QuickMarcEditorRows/MaterialCharsField/ComputerFileMaterialCharsField.js
- src/QuickMarcEditor/QuickMarcEditorRows/MaterialCharsField/ContinuingMaterialCharsField.js
- src/QuickMarcEditor/QuickMarcEditorRows/MaterialCharsField/MapMaterialCharsField.js
- src/QuickMarcEditor/QuickMarcEditorRows/MaterialCharsField/MixedMaterialCharsField.js
- src/QuickMarcEditor/QuickMarcEditorRows/MaterialCharsField/ScoreMaterialCharsField.js
- src/QuickMarcEditor/QuickMarcEditorRows/MaterialCharsField/SoundMaterialCharsField.js
- src/QuickMarcEditor/QuickMarcEditorRows/MaterialCharsField/VisualMaterialCharsField.js
- src/QuickMarcEditor/utils.js
- src/QuickMarcEditor/utils.test.js
- translations/ui-quick-marc/en.json
* Update 006 field
* Add validation
* Add tests
Issue: [UIQM-105](https://issues.folio.org/browse/UIQM-105) …
> UIQM-105: Display MARC Tag 006/00

- src/QuickMarcEditor/QuickMarcEditorRows/MaterialCharsField/BookMaterialCharsField.js
- src/QuickMarcEditor/QuickMarcEditorRows/MaterialCharsField/ComputerFileMaterialCharsField.js
- src/QuickMarcEditor/QuickMarcEditorRows/MaterialCharsField/ContinuingMaterialCharsField.js
- src/QuickMarcEditor/QuickMarcEditorRows/MaterialCharsField/MapMaterialCharsField.js
- src/QuickMarcEditor/QuickMarcEditorRows/MaterialCharsField/MixedMaterialCharsField.js
- src/QuickMarcEditor/QuickMarcEditorRows/MaterialCharsField/ScoreMaterialCharsField.js
- src/QuickMarcEditor/QuickMarcEditorRows/MaterialCharsField/SoundMaterialCharsField.js
- src/QuickMarcEditor/QuickMarcEditorRows/MaterialCharsField/VisualMaterialCharsField.js
Fix of the [comment](https://issues.folio.org/browse/UIQM-105?focusedCommentId=104358&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-104358)
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be …
> UIQM-105: Change Form field on Type for 006 tag field

- CHANGELOG.md
- package.json
Add permission for MARC holdings record
> UIQM-125: Add permission for view, edit MARC holdings record

- CHANGELOG.md
- package.json
- src/QuickMarc.js
- src/QuickMarcEditor/QuickMarcDuplicateWrapper.js
- src/QuickMarcEditor/QuickMarcDuplicateWrapper.test.js
- src/QuickMarcEditor/QuickMarcEditorContainer.js
- src/QuickMarcEditor/QuickMarcEditorContainer.test.js
- src/QuickMarcEditor/utils.test.js
Make changes to API calls and interface version accordion to back-end changes
> UIQM-136 Update according to API change

- CHANGELOG.md
- package.json
- src/QuickMarcEditor/QuickMarcEditorRows/IndicatorField/IndicatorField.js
- src/QuickMarcEditor/QuickMarcEditorRows/IndicatorField/IndicatorField.test.js
increment stripes to v7 and react to v17
[UIQM-130](https://issues.folio.org/browse/UIQM-130)
> UIQM-130: increment stripes to v7 and react to v17

- CHANGELOG.md
- src/QuickMarcEditor/utils.js
- src/QuickMarcEditor/utils.test.js
- translations/ui-quick-marc/en.json
Edit MARC bib record: Update error messaging when entered an invalid value for Leader/05.
Issue: [UIQM-163](https://issues.folio.org/browse/UIQM-163)
> UIQM-163: Edit/Derive quickMARC : Update error messaging when user enters an invalid value for Leader/05

- src/QuickMarcEditor/utils.js
Fix of the [PR](https://github.com/folio-org/ui-quick-marc/pull/242)
> UIQM-181: Fix cleanBytesFields function

- src/QuickMarcEditor/QuickMarcEditorRows/utils.js
Disabled add button for MARC Authorities Leader, 001, 003, 005, 008 fields
[UIQM-142](https://issues.folio.org/browse/UIQM-142)
> UIQM-142 Disabled add button for MARC Auth Leader, 001, 003, 005, 008

- CHANGELOG.md
- src/QuickMarcEditor/QuickMarcCreateWrapper.js
- src/QuickMarcEditor/QuickMarcCreateWrapper.test.js
- src/QuickMarcEditor/QuickMarcEditWrapper.js
- src/QuickMarcEditor/QuickMarcEditWrapper.test.js
- src/QuickMarcEditor/utils.js
- src/QuickMarcEditor/utils.test.js
- translations/ui-quick-marc/en.json
Show error message when MARC Holdings 852 has invalid location value
[UIQM-189](https://issues.folio.org/browse/UIQM-189)
> UIQM-189 Add/Edit MARC holdings: Improve error messaging when user enters an invalid Location (852 ) value

- CHANGELOG.md
- src/QuickMarcEditor/utils.js
- src/QuickMarcEditor/utils.test.js
- translations/ui-quick-marc/en.json
Update error message when user adds multiple 1XXs
[UIQM-196] (https://issues.folio.org/browse/UIQM-196)
https://user-images.githubusercontent.com/96055497/151028872-a0204ea9-be02-47a9-9673-fb3bb1ac673c.mp4
> UIQM-196: Update error message when user adds multiple 1XXs

- src/QuickMarcEditor/utils.js
- src/QuickMarcEditor/utils.test.js
Fix regex that finds location code in 852 subfield
[UIQM-189](https://issues.folio.org/browse/UIQM-189)
> UIQM-189 Fix regex that finds location code

- CHANGELOG.md
- src/QuickMarcEditor/constants.js
Updated 008 default position values
[UIQM-203](https://issues.folio.org/browse/UIQM-203)
https://user-images.githubusercontent.com/96055497/152560991-d5aec3c0-3caa-4bb6-a8f6-40bef8ab1cf1.mp4
> UIQM-203: MARC Holdings Update 008 default position values

- CHANGELOG.md
- src/QuickMarcEditor/QuickMarcCreateWrapper.test.js
- src/QuickMarcEditor/QuickMarcDuplicateWrapper.test.js
- src/QuickMarcEditor/QuickMarcEditWrapper.test.js
- src/QuickMarcEditor/getQuickMarcRecordStatus.test.js
Fix tests that fail due to timeouts on Jenkins.
Issue: [UIQM-202](https://issues.folio.org/browse/UIQM-202)
> UIQM-202: Fix tests that fail due to timeouts on Jenkins

- CHANGELOG.md
- src/QuickMarcView/MarcField.js
- src/QuickMarcView/QuickMarcView.js
- src/QuickMarcView/QuickMarcView.test.js
Highlight clicked on Heading/Reference in Detail record
[UIQM-209](https://issues.folio.org/browse/UIQM-209)
> UIQM-209 Highlight clicked on Heading/Reference in Detail record

- .github/workflows/build-npm-release.yml
- .github/workflows/build-npm.yml
- CHANGELOG.md
- package.json
https://issues.folio.org/browse/UIQM-207 …
> UIQM-207 ui-quick-marc: Configure GitHub actions

- CHANGELOG.md
- package.json
Added permission in package.json
[UIQM-219](https://issues.folio.org/browse/UIQM-219)
> UIQM-219: Cannot assign MARC authority permissions only

- CHANGELOG.md
- package.json
Update stripes-acq-components dep to v3.1.1.
Issue: [UIQM-217](https://issues.folio.org/browse/UIQM-217)
> UIQM-217: Update plugin and components dependencies

- CHANGELOG.md
- package.json
Removed react-hot-loader
[UIQM-224](https://issues.folio.org/browse/UIQM-224)
> UIQM-224: Replace or remove react-hot-loader

- CHANGELOG.md
- src/QuickMarcEditor/QuickMarcDuplicateWrapper.js
- src/QuickMarcEditor/QuickMarcEditWrapper.js
- src/QuickMarcEditor/QuickMarcEditWrapper.test.js
- src/QuickMarcEditor/getQuickMarcRecordStatus.js
- src/QuickMarcEditor/getQuickMarcRecordStatus.test.js
Modify MARC bib processing for update and derive.
[UIQM-235](https://issues.folio.org/browse/UIQM-235)
> UIQM-235: Modify MARC bib processing for update and derive

- CHANGELOG.md
- package.json
- src/QuickMarcEditor/QuickMarcEditWrapper.test.js
- src/QuickMarcEditor/QuickMarcEditor.js
- src/QuickMarcEditor/QuickMarcEditorContainer.js
- translations/ui-quick-marc/en.json
Fix external record path for different marc record types 
https://user-images.githubusercontent.com/19309423/169529684-099a713e-3814-43c0-b238-2463e0f08e3b.mp4
[UIQM-242](https://issues.folio.org/browse/UIQM-242)
> UIQM-242 Apply to MARC Authority:  Optimistic locking: display error message to inform user about OL

- .github/workflows/build-npm-release.yml
- .github/workflows/build-npm.yml
- CHANGELOG.md
- package.json
update NodeJS to v16 in GitHub Actions
[UIQM-241](https://issues.folio.org/browse/UIQM-241)
> UIQM-241 update NodeJS to v16 in GitHub Actions

- package.json
Following https://github.com/folio-org/ui-quick-marc/pull/316, need to update engine version in package.json
> UIQM-241 Updated engine in package.json

- CHANGELOG.md
- src/QuickMarcEditor/QuickMarcRecordInfo/QuickMarcRecordInfo.js
- src/QuickMarcEditor/QuickMarcRecordInfo/QuickMarcRecordInfo.test.js
Fixed undefined user name
[UIQM-244](https://issues.folio.org/browse/UIQM-244)
https://user-images.githubusercontent.com/96055497/172416911-f15d01b3-733d-4240-94c7-6059ed6bdc40.mp4
> UIQM-244: Fix undefined user name

- CHANGELOG.md
- package.json
Release commits for `5.0.2` and `5.0.3` releases
> Release v5.0.2, v5.0.3

- .eslintrc
- CHANGELOG.md
- src/QuickMarcEditor/QuickMarcEditWrapper.js
- src/QuickMarcEditor/QuickMarcEditWrapper.test.js
- src/QuickMarcEditor/QuickMarcEditor.js
- translations/ui-quick-marc/en.json
Add toast notification when a user updates the record but the record has already been deleted.
https://user-images.githubusercontent.com/77053927/180420466-73440fb0-b30c-4a88-8c7b-f31416289659.mp4
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount …
> UIQM-259: Edit MARC authority: User does not get a notification that the record is edited has been deleted by another user

- CHANGELOG.md
- src/QuickMarcEditor/QuickMarcEditorContainer.js
- src/QuickMarcEditor/QuickMarcEditorContainer.test.js
- src/QuickMarcEditor/QuickMarcEditorRows/LocationField/LocationField.js
- src/QuickMarcEditor/QuickMarcEditorRows/LocationField/LocationField.test.js
- src/QuickMarcEditor/QuickMarcEditorRows/QuickMarcEditorRows.js
- src/QuickMarcEditor/utils.js
Fix `<LocationField>` so user can enter text
Fix moving fields causes them to copy values
https://user-images.githubusercontent.com/19309423/182122419-c2ad2830-ce6f-4552-aed4-68867ab2f350.mp4
[UIQM-260](https://issues.folio.org/browse/UIQM-260)
> UIQM-260: Add MARC holdings:  852 field > cannot enter text 

- CHANGELOG.md
- src/QuickMarcEditor/utils.js
- src/QuickMarcEditor/utils.test.js
Remove default subfield $a for 852 field
[UIQM-269](https://issues.folio.org/browse/UIQM-269)
> UIQM-269 Remove default subfield $a for 852 field

- CHANGELOG.md
- src/QuickMarcView/QuickMarcView.js
see PR of [UIPFAUTH-5](https://github.com/folio-org/ui-plugin-find-authority/pull/18)
While …
> UIQM-278: Add the ability to change the height of the QuickMarcView component.

- CHANGELOG.md
- package.json
- src/QuickMarcEditor/QuickMarcEditorRows/QuickMarcEditorRows.js
- translations/ui-quick-marc/en.json
New permission: quickMARC Link/unlink authority records to bib records
While it's helpful …
> UIQM-254: New permission: quickMARC Link/unlink authority records to bib records

- CHANGELOG.md
- src/QuickMarcEditor/QuickMarcCreateWrapper.js
- src/QuickMarcEditor/QuickMarcDuplicateWrapper.js
- src/QuickMarcEditor/QuickMarcEditorRows/DeletedRowPlaceholder/DeletedRowPlaceholder.css
- src/QuickMarcEditor/QuickMarcEditorRows/DeletedRowPlaceholder/DeletedRowPlaceholder.js
- src/QuickMarcEditor/QuickMarcEditorRows/DeletedRowPlaceholder/DeletedRowPlaceholder.test.js
- src/QuickMarcEditor/QuickMarcEditorRows/DeletedRowPlaceholder/index.js
- src/QuickMarcEditor/QuickMarcEditorRows/QuickMarcEditorRows.js
- translations/ui-quick-marc/en.json
Show placeholders in place of deleted rows
https://user-images.githubusercontent.com/19309423/186903184-8c136a48-e1ac-43f7-b46d-777712e28a8d.mp4
[UIQM-270](https://issues.folio.org/browse/UIQM-270)
> UIQM-270 Added placeholder for deleted fields

- CHANGELOG.md
- src/QuickMarcEditor/QuickMarcEditor.js
Remove the deletion of entered data when the user clicks the "Save & close" button and a validation error appears.
[UIQM-289](https://issues.folio.org/browse/UIQM-289)
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, …
> UIQM-289: The entered data is deleted when user click on the "Save & close" button and validation error appears

- CHANGELOG.md
- src/QuickMarcEditor/QuickMarcEditWrapper.test.js
- src/QuickMarcEditor/QuickMarcEditor.js
- src/QuickMarcEditor/QuickMarcEditorRows/LinkButton/LinkButton.js
- src/QuickMarcEditor/QuickMarcEditorRows/LinkButton/LinkButton.test.js
- src/QuickMarcEditor/QuickMarcEditorRows/LinkButton/index.js
- src/QuickMarcEditor/QuickMarcEditorRows/QuickMarcEditorRows.js
- src/QuickMarcEditor/utils.js
- src/QuickMarcEditor/utils.test.js
- translations/ui-quick-marc/en.json
Handle linking of Authority record
https://user-images.githubusercontent.com/19309423/189623412-0061a2bd-964d-43fa-b13e-49309e9d066d.mp4
[UIQM-290](https://issues.folio.org/browse/UIQM-290)
https://github.com/folio-org/ui-plugin-find-authority/pull/27
> UIQM-290 Detail Record : Click Link button to select a MARC authority record

- .eslintrc
- CHANGELOG.md
- src/QuickMarcEditor/QuickMarcEditorRows/QuickMarcEditorRows.css
- src/QuickMarcEditor/QuickMarcEditorRows/QuickMarcEditorRows.js
- src/QuickMarcEditor/QuickMarcEditorRows/QuickMarcEditorRows.test.js
- test/jest/__mock__/index.js
- test/jest/__mock__/stripesCore.mock.js
- translations/ui-quick-marc/en.json
Add the `eye-open` icon to navigate to the view MARC authority record source in a new tab.
[UIQM-284](https://issues.folio.org/browse/UIQM-284)
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number …
> UIQM-284: Linked bib field | Show View Authority icon

- CHANGELOG.md
- package.json
- src/QuickMarcEditor/QuickMarcEditor.test.js
- src/QuickMarcEditor/QuickMarcEditorContainer.test.js
- src/QuickMarcEditor/QuickMarcEditorRows/QuickMarcEditorRows.test.js
- src/hooks/index.js
- src/hooks/useAuthorityLinking/useAuthorityLinking.js
- src/hooks/useAuthorityLinking/useAuthorityLinking.test.js
- src/hooks/useAuthoritySourceFiles/index.js
- src/hooks/useAuthoritySourceFiles/useAuthoritySourceFiles.js
- src/hooks/useAuthoritySourceFiles/useAuthoritySourceFiles.test.js
- test/jest/__mock__/index.js
- test/jest/__mock__/stripesAuthorityComponents.mock.js
Remove the dependency on `stripes-authority-components`. 
While it's helpful for reviewers …
> UIQM-305: Resolve ui-quick-marc and stripes-authority-component circular dependency

- CHANGELOG.md
- src/QuickMarcEditor/QuickMarcDuplicateWrapper.test.js
- src/QuickMarcEditor/constants.js
- src/QuickMarcEditor/utils.test.js
Add validation for positions 18 and 19.
[UIQM-311](https://issues.folio.org/browse/UIQM-311)
https://user-images.githubusercontent.com/77053927/195564170-eda1669d-328f-41d5-88fd-20b5cc128e1e.mp4
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if …
> UIQM-311: Edit/Derive MARC bib | Improve error messaging for Leader positions 18 and 19

- CHANGELOG.md
- src/QuickMarcEditor/QuickMarcEditor.css
- src/QuickMarcEditor/QuickMarcEditor.js
Update spacing between Save & continue and Save & close buttons
[UIQM-310](https://issues.folio.org/browse/UIQM-310)
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and …
> UIQM-310: Update spacing between Save & continue and Save & close buttons

- CHANGELOG.md
- src/QuickMarcEditor/QuickMarcEditorRows/QuickMarcEditorRows.js
- src/QuickMarcEditor/QuickMarcEditorRows/QuickMarcEditorRows.test.js
Authority control: Hide link authority button before Nolana release
Issue: https://issues.folio.org/browse/UIQM-288 …
> UIQM-288-Authority control: Hide link authority button before Nolana release

- CHANGELOG.md
- src/QuickMarcEditor/QuickMarcCreateWrapper.test.js
- src/QuickMarcEditor/QuickMarcDuplicateWrapper.js
- src/QuickMarcEditor/QuickMarcDuplicateWrapper.test.js
- src/QuickMarcEditor/QuickMarcEditWrapper.test.js
- src/QuickMarcEditor/QuickMarcEditor.js
- src/QuickMarcEditor/QuickMarcEditor.test.js
- translations/ui-quick-marc/en.json
FE | Linked bib fields | Derive a new MARC bibliographic record handling.
Issue: [UIQM-281](https://issues.folio.org/browse/UIQM-281)
Better idea of Marc Bib records and Authority Records
1. When logged in with diku user
2. When logged in with other user who does not have permission "ui-quick-marc.quick-marc-authority-records.linkUnlink"
3. When Marc Bib Record is not linked with any authority record.
- Are the JIRAs under active …
> UIQM-281 - FE | Linked bib fields | Derive a new MARC bibliographic record handling

- CHANGELOG.md
- src/QuickMarcEditor/QuickMarcEditorRows/LinkButton/LinkButton.js
- src/QuickMarcEditor/QuickMarcEditorRows/LinkButton/LinkButton.test.js
- src/QuickMarcEditor/QuickMarcEditorRows/QuickMarcEditorRows.js
- src/QuickMarcEditor/QuickMarcEditorRows/QuickMarcEditorRows.test.js
- src/hooks/useAuthorityLinking/useAuthorityLinking.js
- src/hooks/useAuthorityLinking/useAuthorityLinking.test.js
- src/queries/useMarcSource/useMarcSource.js
- src/queries/useMarcSource/useMarcSource.test.js
Link then Unlink bib field before saving record behavior
[UIQM-307](https://issues.folio.org/browse/UIQM-307)
https://user-images.githubusercontent.com/77053927/198146734-35ac5aa1-3358-4def-ab92-175a1336325e.mp4
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment. …
> UIQM-307: Link then Unlink bib field before saving record behavior

- CHANGELOG.md
- package.json
- src/QuickMarc.test.js
- src/QuickMarcEditor/OptimisticLockingBanner/OptimisticLockingBanner.test.js
- src/QuickMarcEditor/QuickMarcCreateWrapper.test.js
- src/QuickMarcEditor/QuickMarcDuplicateWrapper.test.js
- src/QuickMarcEditor/QuickMarcEditWrapper.test.js
- src/QuickMarcEditor/QuickMarcEditor.test.js
- src/QuickMarcEditor/QuickMarcEditorContainer.test.js
- src/QuickMarcEditor/QuickMarcEditorRows/BytesField/BytesField.test.js
- src/QuickMarcEditor/QuickMarcEditorRows/ContentField/ContentField.test.js
- src/QuickMarcEditor/QuickMarcEditorRows/IndicatorField/IndicatorField.test.js
- src/QuickMarcEditor/QuickMarcEditorRows/LinkButton/LinkButton.test.js
- src/QuickMarcEditor/QuickMarcEditorRows/QuickMarcEditorRows.test.js
- src/QuickMarcEditor/QuickMarcRecordInfo/QuickMarcRecordInfo.test.js
- src/QuickMarcView/QuickMarcView.test.js
- src/queries/useMarcSource/useMarcSource.test.js
- test/jest/helpers/harness.js
- test/jest/helpers/intl.js
Create a test Harness for quick marc tests
[UIQM-312](https://issues.folio.org/browse/UIQM-312)
> UIQM-312 Create a test Harness for quick marc tests

- CHANGELOG.md
- package.json
- src/QuickMarc.js
- src/QuickMarc.test.js
- src/QuickMarcEditor/QuickMarcCreateWrapper.js
- src/QuickMarcEditor/QuickMarcDeriveWrapper.js
- src/QuickMarcEditor/QuickMarcDeriveWrapper.test.js
- src/QuickMarcEditor/QuickMarcEditWrapper.js
- src/QuickMarcEditor/QuickMarcEditorContainer.test.js
- src/QuickMarcEditor/QuickMarcEditorRows/QuickMarcEditorRows.js
- src/QuickMarcEditor/QuickMarcEditorRows/QuickMarcEditorRows.test.js
- src/QuickMarcEditor/QuickMarcEditorRows/utils.js
- src/QuickMarcEditor/QuickMarcEditorRows/utils.test.js
- src/QuickMarcEditor/constants.js
- src/QuickMarcEditor/index.js
- src/QuickMarcEditor/utils.js
- src/QuickMarcEditor/utils.test.js
- translations/ui-quick-marc/en.json
Rename "Duplicate BIB" feature to "Derive BIB" feature
[UIQM-315](https://issues.folio.org/browse/UIQM-315)
> UIQM-315 Rename "Duplicate BIB" feature to "Derive BIB" feature

- CHANGELOG.md
- package.json
Reveal the permission `quickMARC: Can Link/unlink authority records to bib records`.
[UIQM-320](https://issues.folio.org/browse/UIQM-320)
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of …
> UIQM-320: The permission "quickMARC: Can Link/unlink authority records to bib records" is hidden on UI.

- CHANGELOG.md
Release v5.1.3
While it's helpful for reviewers to help identify potential problems, …
> Release v5.1.3

- CHANGELOG.md
- package.json
- src/QuickMarcEditor/QuickMarcEditorRows/LinkButton/LinkButton.js
- src/QuickMarcEditor/QuickMarcEditorRows/LinkButton/LinkButton.test.js
- src/QuickMarcEditor/QuickMarcEditorRows/QuickMarcEditorRows.js
- src/QuickMarcEditor/QuickMarcEditorRows/QuickMarcEditorRows.test.js
- src/common/constants/defaultLookup.js
- src/common/constants/filters.js
- src/common/constants/index.js
- src/common/constants/searchableIndexesValues.js
- src/hooks/useAuthorityLinking/useAuthorityLinking.js
Add default lookup options
[UIQM-332](https://issues.folio.org/browse/UIQM-332)
[UIPFAUTH-36](https://github.com/folio-org/ui-plugin-find-authority/pull/47)
[UISAUTCOMP-33](https://github.com/folio-org/stripes-authority-components/pull/48) …
> UIQM-332: Default search/browse option and Authority source file selections based on MARC bib field to be linked 

- CHANGELOG.md
- src/QuickMarcEditor/QuickMarcCreateWrapper.js
- src/QuickMarcEditor/QuickMarcDeriveWrapper.js
- src/QuickMarcEditor/QuickMarcEditWrapper.js
- src/QuickMarcEditor/QuickMarcEditWrapper.test.js
- src/QuickMarcEditor/QuickMarcEditor.js
- src/QuickMarcEditor/QuickMarcEditor.test.js
- src/QuickMarcEditor/utils.js
- src/QuickMarcEditor/utils.test.js
- src/queries/index.js
- src/queries/useAuthorityLinksCount/index.js
- src/queries/useAuthorityLinksCount/useAuthorityLinksCount.js
- src/queries/useAuthorityLinksCount/useAuthorityLinksCount.test.js
- translations/ui-quick-marc/en.json
Add validation for linked authority 1XX field.
[UIQM-322](https://issues.folio.org/browse/UIQM-322)
https://user-images.githubusercontent.com/77053927/208175947-667417b3-62ef-42d7-b51c-dc1923474a2c.mp4 …
> UIQM-322: Edit MARC authority app | User edits the 1XX value and has linked bib fields

- src/QuickMarcEditor/QuickMarcEditWrapper.js
- src/QuickMarcEditor/QuickMarcEditWrapper.test.js
- src/QuickMarcEditor/QuickMarcEditor.js
- src/QuickMarcEditor/utils.js
- src/QuickMarcEditor/utils.test.js
- translations/ui-quick-marc/en.json
Show confirmation for all authRefTypes
Close confirmation modals when validation error appears
[UIQM-331](https://issues.folio.org/browse/UIQM-331)
> UIQM-331 Edit MARC authority: Handling updates 1XX or 010 $a value 

- CHANGELOG.md
- package.json
Update `inventory` interface 
[UIQM-349](https://issues.folio.org/browse/UIQM-349)
> UIQM-349 Align the module with API breaking change

- src/QuickMarcView/MarcContent/MarcContent.js
- src/QuickMarcView/MarcField.js
- src/QuickMarcView/PrintPopup/PrintPopup.js
Supplement to requirements from the [comment](https://issues.folio.org/browse/UIQM-335?focusedCommentId=154609&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-154609): Remove the display of the link to the marc-authority app when printing.
[UIQM-335](https://issues.folio.org/browse/UIQM-335?devStatusDetailDialog=pullrequest)
https://user-images.githubusercontent.com/77053927/212015097-04fd75b6-3a8f-494c-93b8-c66715ddb87b.mp4
- Do JIRAs exist to …
> UIQM-335: Remove the display of the link to the marc-authority app when printing

- src/QuickMarcView/MarcContent/MarcContent.js
- src/QuickMarcView/MarcField.js
- src/QuickMarcView/PrintPopup/PrintPopup.js
Reverts folio-org/ui-quick-marc#428
> Revert "UIQM-335: Remove the display of the link to the marc-authority app when printing"

- CHANGELOG.md
- package.json
bump stripes to 8.0.0
[UIQM-368](https://issues.folio.org/browse/UIQM-368)
While it's …
> UIQM-368: bump stripes to 8.0.0 for Orchid/2023-R1

- CHANGELOG.md
- src/QuickMarcEditor/QuickMarcEditor.js
- translations/ui-quick-marc/en.json
Rename the modal message and button name.
[UIQM-359](https://issues.folio.org/browse/UIQM-359)
https://user-images.githubusercontent.com/77053927/212911027-657cbce4-98db-47c8-94f2-51dfda67aed1.mp4
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount …
> UIQM-359: Change to Linked MARC authority record has been updated confirmation messaging 

- src/QuickMarcView/PrintPopup/PrintPopup.js
According to the [comment](https://issues.folio.org/browse/UIQM-335?focusedCommentId=155354&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-155354): after clicking the `Print` button the landscape layout should be displayed horizontally in the PDF file.
[UIQM-335](https://issues.folio.org/browse/UIQM-335)
https://user-images.githubusercontent.com/77053927/213458148-eaae8bbb-004d-44e5-a1a6-88798ef95b29.mp4
- Do JIRAs exist to update the impacted …
> UIQM-335: Avoid rotation in PDF files when a user saves the landscape layout.

- package.json
Update of the major version due to the update of the stripes.
[UIQM-368](https://issues.folio.org/browse/UIQM-368) …
> UIQM-368: Change version to 6.0.0

- CHANGELOG.md
- src/QuickMarcView/MarcField.js
Open an authorized record after clicking on the `MARC Authority` icon.
[UIQM-376](https://issues.folio.org/browse/UIQM-376)
https://user-images.githubusercontent.com/77053927/214103126-b8fdc3db-eee7-4012-9c00-efe4c30d3c08.mp4
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment. …
> UIQM-376: Reference MARC Authority record is opened when user clicks on the "MARC Authority" icon next to the controlled field

- CHANGELOG.md
- src/QuickMarcEditor/utils.js
Fix exception when changing field from any to 010
https://user-images.githubusercontent.com/19309423/215731034-f4c19e18-08fb-44a6-9fba-93d003c9b82f.mp4
[UIQM-390](https://issues.folio.org/browse/UIQM-390)
> UIQM-390 "Something went wrong" message when changing tag value to "010" in "MARC authority" record without "010" field

- CHANGELOG.md
- src/hooks/useAuthorityLinking/useAuthorityLinking.js
- src/hooks/useAuthorityLinking/useAuthorityLinking.test.js
Do not append `http://` after linking.
[UIQM-375](https://issues.folio.org/browse/UIQM-375)
https://user-images.githubusercontent.com/77053927/216017007-d3fc3e0c-dffe-45f5-ac1c-1e22173bdad3.mp4
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if …
> UIQM-375: Do not add "http://" to "base url" when user links "MARC Bib's" field with "MARC Authority"

- src/QuickMarcEditor/utils.js
- src/QuickMarcEditor/utils.test.js
- translations/ui-quick-marc/en.json
Fix translation. 
Split the translation into two separate ones in order to not complicate it.
[UIQM-367](https://issues.folio.org/browse/UIQM-367)
https://user-images.githubusercontent.com/77053927/216570580-c436db11-3f28-448a-abb3-896a6e12b040.mp4 …
> UIQM-367: Revise translations

- CHANGELOG.md
- src/QuickMarcEditor/QuickMarcEditWrapper.js
- src/QuickMarcEditor/QuickMarcEditor.js
- src/QuickMarcEditor/utils.js
- src/QuickMarcEditor/utils.test.js
- translations/ui-quick-marc/en.json
Show a toast notification when a user edits the authority 010 $a and the linking is based on 001.
[UIQM-386](https://issues.folio.org/browse/UIQM-386)
https://user-images.githubusercontent.com/77053927/216369106-b28eefaa-d12c-4556-ab79-b55739be75a8.mp4 …
> UIQM-386: Edit MARC authority | Add/Edit 010 $a when linking is based on 001.

- CHANGELOG.md
- src/QuickMarcEditor/QuickMarcDeriveWrapper.js
- src/QuickMarcEditor/utils.js
- src/hooks/useAuthorityLinking/useAuthorityLinking.js
Add `linkingRuleId` to the request body for linked fields
[UIQM-402](https://issues.folio.org/browse/UIQM-402) …
> UIQM-402: Add linkingRuleId to the request body for linked fields

- CHANGELOG.md
Release 6.0.0
While it's helpful for reviewers to help identify potential problems, ensuring …
> Release 6.0.0

- CHANGELOG.md
- src/QuickMarcEditor/QuickMarcEditWrapper.js
- src/QuickMarcEditor/QuickMarcEditorRows/QuickMarcEditorRows.js
- src/QuickMarcEditor/utils.js
- src/QuickMarcEditor/utils.test.js
- translations/ui-quick-marc/en.json
https://user-images.githubusercontent.com/19309423/226913879-a8b3e180-bc10-4ba8-a4df-120f0f05b4b8.mp4
[UIQM-426](https://issues.folio.org/browse/UIQM-426)
> UIQM-426 Allow a user to manual enter/edit  for non-linkable/non-controllable bib field

- CHANGELOG.md
- src/QuickMarcEditor/QuickMarcDeriveWrapper.js
Show error if $9 is added during deriving.
[UIQM-426](https://issues.folio.org/browse/UIQM-426?focusedCommentId=163876&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-163876)
https://user-images.githubusercontent.com/77053927/228337667-1d24743a-cff1-4bdf-b572-84111cb3b3b5.mp4
Ideally all of the PRs involved in breaking …
> UIQM-426: Show error if $9 is added during deriving.

- CHANGELOG.md
- src/QuickMarcEditor/QuickMarcEditorRows/SplitField/SplitField.js
Disable pressing Enter for linked fields.
[UIQM-424](https://issues.folio.org/browse/UIQM-424)
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies …
> UIQM-424: Disable pressing Enter for linked fields.

- CHANGELOG.md
- package.json
> Release v6.0.2

- CHANGELOG.md
- test/jest/helpers/harness.js
https://issues.folio.org/browse/UIQM-432
Avoid private paths in stripes-core imports
> UIQM-432: Avoid private paths in stripes-core imports

- CHANGELOG.md
- src/QuickMarcEditor/QuickMarcEditorRows/LinkButton/LinkButton.js
- src/QuickMarcEditor/QuickMarcEditorRows/LinkButton/LinkButton.test.js
- src/QuickMarcEditor/QuickMarcEditorRows/QuickMarcEditorRows.js
- src/common/constants/defaultLookup.js
- src/common/constants/index.js
- src/common/constants/navigationSegments.js
Update initial values passed to Find Authority plugin
https://user-images.githubusercontent.com/19309423/231174339-a620992d-175b-4a02-ba2b-a904b78f1ef0.mp4
[UIQM-449](https://issues.folio.org/browse/UIQM-449)
https://github.com/folio-org/stripes-authority-components/pull/72
> UIQM-449 Pre-populate search/browse box with bib subfield values 

- package.json
- src/QuickMarcEditor/QuickMarcEditorRows/LinkButton/LinkButton.js
- src/QuickMarcEditor/QuickMarcEditorRows/LinkButton/LinkButton.test.js
Pass initial values for search and browse at the same time
https://user-images.githubusercontent.com/19309423/233059736-fd5048c3-947f-450d-9cc7-c0232a874734.mp4
[UIQM-449](https://issues.folio.org/browse/UIQM-449)
> UIQM-449 Support default parameters for both search and browse together

- src/QuickMarcEditor/QuickMarcEditorRows/LinkButton/LinkButton.js
- src/QuickMarcEditor/QuickMarcEditorRows/LinkButton/LinkButton.test.js
Fix index is not set correctly for requests
[UIQM-449](https://issues.folio.org/browse/UIQM-449)
> UIQM-449 Set default search index

- CHANGELOG.md
- src/QuickMarcEditor/QuickMarcRecordInfo/QuickMarcRecordInfo.js
- src/QuickMarcEditor/QuickMarcRecordInfo/QuickMarcRecordInfo.test.js
Fix display person who last edited quickMARC record. 
[UIQM-423](https://issues.folio.org/browse/UIQM-423) …
> UIQM-423 Fix display person who last edited quickMARC record

- CHANGELOG.md
- src/QuickMarcEditor/QuickMarcDeriveWrapper.js
- src/QuickMarcEditor/utils.js
- src/QuickMarcEditor/utils.test.js
Remove 001 fields when creating/deriving marc records
https://user-images.githubusercontent.com/19309423/234571749-7a7e2cd4-c926-41c3-8863-294834362c23.mp4
[UIQM-448](https://issues.folio.org/browse/UIQM-448)
> UIQM-448 Fix validation of 001 fields when creating/deriving/editing all record types.

- src/QuickMarcEditor/QuickMarcCreateWrapper.js
Pass linking rules to validation when creating marc records
[UIQM-415](https://issues.folio.org/browse/UIQM-415)
> UIQM-415 Pass linking rules to validation in create

- CHANGELOG.md
- src/QuickMarcEditor/QuickMarcCreateWrapper.js
- src/QuickMarcEditor/QuickMarcDeriveWrapper.js
- src/QuickMarcEditor/QuickMarcEditWrapper.js
- src/QuickMarcEditor/QuickMarcEditorRows/QuickMarcEditorRows.js
- src/QuickMarcEditor/utils.js
- src/QuickMarcEditor/utils.test.js
Remove user defined 001 fields
Use lodash flow to chain marc record save preparation
[UIQM-448](https://issues.folio.org/browse/UIQM-448)
> UIQM-448 Remove user defined 001 fields when editing

- src/QuickMarcEditor/QuickMarcCreateWrapper.js
- src/QuickMarcEditor/QuickMarcDeriveWrapper.js
- src/QuickMarcEditor/QuickMarcDeriveWrapper.test.js
- src/QuickMarcEditor/utils.js
`POST` method doesn't support linking so we need to make an additional `PUT` to update newly created bib with links
https://user-images.githubusercontent.com/19309423/235900829-0d401641-bee2-4124-a459-e1619ba0225e.mp4
[UIQM-415](https://issues.folio.org/browse/UIQM-415)
> UIQM-415 Make update request when creating bib to save links

- src/QuickMarcEditor/QuickMarcCreateWrapper.js
Fix not controlled fields not saved in linked fields
https://user-images.githubusercontent.com/19309423/236455897-42481750-dac0-4a1f-b64c-396cc35b55d3.mp4
[UIQM-415](https://issues.folio.org/browse/UIQM-415)
> UIQM-415 Combine split fields before creating marc bib

- CHANGELOG.md
- package.json
Add permission for editing MARC Holdings records.
[UIQM-470](https://issues.folio.org/browse/UIQM-470)
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies …
> UIQM-470: Add permission for editing MARC Holdings records.

- CHANGELOG.md
- src/QuickMarcEditor/QuickMarcEditorRows/BytesField/BytesField.test.js
- src/QuickMarcEditor/QuickMarcEditorRows/FixedField/BookFixedField.js
- src/QuickMarcEditor/QuickMarcEditorRows/FixedField/ComputerFileFixedField.js
- src/QuickMarcEditor/QuickMarcEditorRows/FixedField/ContinuingResourceFixedField.js
- src/QuickMarcEditor/QuickMarcEditorRows/FixedField/MapFixedField.js
- src/QuickMarcEditor/QuickMarcEditorRows/FixedField/MixedMaterialFixedField.js
- src/QuickMarcEditor/QuickMarcEditorRows/FixedField/ScoreFixedField.js
- src/QuickMarcEditor/QuickMarcEditorRows/FixedField/SoundRecordingFixedField.js
- src/QuickMarcEditor/QuickMarcEditorRows/FixedField/VisualMaterialFixedField.js
- src/QuickMarcEditor/constants.js
Remove unused `Ctrl` field from `008`
[UIQM-465](https://issues.folio.org/browse/UIQM-465)
> UIQM-465 Bib Rec. / Field 008 / Ctrl / Removing

- CHANGELOG.md
- src/QuickMarcEditor/QuickMarcCreateWrapper.js
- src/QuickMarcEditor/QuickMarcDeriveWrapper.js
- src/QuickMarcEditor/QuickMarcEditWrapper.js
- src/QuickMarcEditor/QuickMarcEditorRows/BytesField/BytesField.js
- src/QuickMarcEditor/QuickMarcEditorRows/FixedField/AuthorityFixedField.js
- src/QuickMarcEditor/QuickMarcEditorRows/FixedField/BookFixedField.js
- src/QuickMarcEditor/QuickMarcEditorRows/FixedField/ComputerFileFixedField.js
- src/QuickMarcEditor/QuickMarcEditorRows/FixedField/ContinuingResourceFixedField.js
- src/QuickMarcEditor/QuickMarcEditorRows/FixedField/HoldingsFixedField.js
- src/QuickMarcEditor/QuickMarcEditorRows/FixedField/MapFixedField.js
- src/QuickMarcEditor/QuickMarcEditorRows/FixedField/MixedMaterialFixedField.js
- src/QuickMarcEditor/QuickMarcEditorRows/FixedField/ScoreFixedField.js
- src/QuickMarcEditor/QuickMarcEditorRows/FixedField/SoundRecordingFixedField.js
- src/QuickMarcEditor/QuickMarcEditorRows/FixedField/VisualMaterialFixedField.js
- src/QuickMarcEditor/constants.js
- src/QuickMarcEditor/getQuickMarcRecordStatus.js
- src/QuickMarcEditor/utils.js
- src/QuickMarcEditor/utils.test.js
Added lengths for Fixed fields
Setting default values based on field length
https://github.com/folio-org/ui-quick-marc/assets/19309423/5b13070e-7c08-4fd6-8389-b70f53380421
[UIQM-464](https://issues.folio.org/browse/UIQM-464)
> UIQM-464 Create Orig Bib Record: Populate new record with 008

- CHANGELOG.md
- src/QuickMarcEditor/QuickMarcEditorRows/LinkButton/LinkButton.js
- src/QuickMarcEditor/QuickMarcEditorRows/LinkButton/LinkButton.test.js
Always conduct an Advanced search when $0 is present
[UIQM-496](https://issues.folio.org/browse/UIQM-496)
https://github.com/folio-org/ui-quick-marc/assets/77053927/d410c0e3-a355-4b22-bd33-61d545fb37e2 …
> UIQM-496: Conduct an Advanced search when $0 is present

- src/QuickMarcEditor/QuickMarcEditorRows/FixedField/HoldingsFixedField.js
- src/QuickMarcEditor/constants.js
- src/QuickMarcEditor/utils.js
- src/QuickMarcEditor/utils.test.js
Added missing hidden fields when editing Authority records
[UIQM-492](https://issues.folio.org/browse/UIQM-492)
> UIQM-492 Fix incorrect 008 field length Authority

- CHANGELOG.md
- src/QuickMarcEditor/QuickMarcDeriveWrapper.js
- src/QuickMarcEditor/constants.js
- src/QuickMarcEditor/utils.js
- src/QuickMarcEditor/utils.test.js
Remove 008 Entered fields before sending record to Derive
[UIQM-500](https://issues.folio.org/browse/UIQM-500)
> UIQM-500 Remove 008 Entered field when Deriving a record.

- CHANGELOG.md
- src/QuickMarcEditor/QuickMarcCreateWrapper.js
- src/QuickMarcEditor/QuickMarcDeriveWrapper.js
- src/QuickMarcEditor/QuickMarcEditWrapper.js
- src/QuickMarcEditor/QuickMarcEditorContainer.js
- src/QuickMarcEditor/QuickMarcEditorRows/MaterialCharsField/MediaMaterialCharsFieldConfig.js
- src/QuickMarcEditor/QuickMarcEditorRows/PhysDescriptionField/ElResourcePhysDescriptionFieldConfig.js
- src/QuickMarcEditor/QuickMarcEditorRows/PhysDescriptionField/MicroformDescriptionFieldConfig.js
- src/QuickMarcEditor/QuickMarcEditorRows/PhysDescriptionField/PicturePhysDescriptionFieldConfig.js
- src/QuickMarcEditor/QuickMarcEditorRows/PhysDescriptionField/RSImagePhysDescriptionFieldConfig.js
- src/QuickMarcEditor/QuickMarcEditorRows/PhysDescriptionField/TactilePhysDescriptionFieldConfig.js
- src/QuickMarcEditor/utils.js
- src/QuickMarcEditor/utils.test.js
Auto-populate empty positions for fields 006, 007 and 008.
[UIQM-499](https://issues.folio.org/browse/UIQM-499)
https://github.com/folio-org/ui-quick-marc/assets/77053927/eb14b316-c962-438d-b6ef-2099227dafb5 …
> UIQM-499: Auto-populate empty positions for fields 006, 007 and 008.

- package.json
> UIQM-326: Add permission for auto-linking.

- CHANGELOG.md
- src/QuickMarcEditor/AutoLinkingButton/AutoLinkingButton.js
- src/QuickMarcEditor/AutoLinkingButton/AutoLinkingButton.test.js
- src/QuickMarcEditor/QuickMarcCreateWrapper.js
- src/QuickMarcEditor/QuickMarcCreateWrapper.test.js
- src/QuickMarcEditor/QuickMarcDeriveWrapper.js
- src/QuickMarcEditor/QuickMarcDeriveWrapper.test.js
- src/QuickMarcEditor/QuickMarcEditWrapper.js
- src/QuickMarcEditor/QuickMarcEditWrapper.test.js
- src/QuickMarcEditor/QuickMarcEditorRows/SplitField/SplitField.js
- src/QuickMarcEditor/constants.js
- src/QuickMarcEditor/utils.js
- src/hooks/useAuthorityLinking/useAuthorityLinking.js
- src/hooks/useAuthorityLinking/useAuthorityLinking.test.js
- src/queries/useLinkSuggestions/useLinkSuggestions.js
- src/queries/useLinkSuggestions/useLinkSuggestions.test.js
Actualize linked fields on save.
[UIQM-501](https://issues.folio.org/browse/UIQM-501)
https://github.com/folio-org/ui-quick-marc/assets/77053927/a1646a51-a388-4e4d-8e35-e75f0c6b50f2
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to …
> UIQM-501: Actualize linked fields on save.

- CHANGELOG.md
- src/QuickMarcEditor/QuickMarcEditor.js
- src/QuickMarcEditor/utils.js
- translations/ui-quick-marc/en.json
Add "Local" or "Shared" to flag MARC bib records
https://github.com/folio-org/ui-quick-marc/assets/19309423/22653b15-75fe-4f97-9eb1-725356e35624
[UIQM-483](https://issues.folio.org/browse/UIQM-483)
https://github.com/folio-org/ui-inventory/pull/2230
> UIQM-483 Add "Local" or "Shared" to flag MARC bib records

- .github/workflows/build-npm-release.yml
- .github/workflows/build-npm.yml
- CHANGELOG.md
- package.json
Update Node.js to v18 in GitHub Actions
[UIQM-535](https://issues.folio.org/browse/UIQM-535)
> UIQM-535 Update Node.js to v18 in GitHub Actions

- CHANGELOG.md
- src/QuickMarcEditor/QuickMarcCreateWrapper.test.js
- translations/ui-quick-marc/en.json
Add `Local` or `Shared` to flag MARC authorities.
https://github.com/folio-org/ui-plugin-find-authority/pull/72
https://github.com/folio-org/ui-marc-authorities/pull/304
https://github.com/folio-org/stripes-authority-components/pull/94
[UIQM-544](https://issues.folio.org/browse/UIQM-544)
Ideally all of the PRs involved in breaking changes would be merged …
> UIQM-544: Add 'Local' or 'Shared' to flag MARC authorities.

- CHANGELOG.md
- src/MarcRoute/MarcRoute.js
- src/QuickMarc.js
- src/QuickMarcEditor/QuickMarcEditWrapper.js
- src/QuickMarcEditor/QuickMarcEditWrapper.test.js
- src/QuickMarcEditor/QuickMarcEditor.js
- src/QuickMarcEditor/QuickMarcEditor.test.js
- src/QuickMarcEditor/QuickMarcEditorContainer.js
- src/QuickMarcEditor/QuickMarcEditorContainer.test.js
- src/QuickMarcEditor/QuickMarcEditorRows/LinkButton/LinkButton.js
- src/QuickMarcEditor/QuickMarcEditorRows/LinkButton/LinkButton.test.js
- src/QuickMarcEditor/QuickMarcEditorRows/QuickMarcEditorRows.js
- src/QuickMarcEditor/utils.js
- src/queries/useMarcSource/useMarcSource.js
- src/temp/index.js
- src/temp/useTenantKy/index.js
- src/temp/useTenantKy/useTenantKy.js
- src/temp/useTenantKy/useTenantKy.test.js
Link Shared/Local MARC bib record to Shared/Local Authority record.
[UIQM-547](https://issues.folio.org/browse/UIQM-547)
https://github.com/folio-org/stripes-authority-components/pull/100
https://github.com/folio-org/ui-plugin-find-authority/pull/75
https://github.com/folio-org/ui-inventory/pull/2242
https://github.com/folio-org/ui-quick-marc/assets/77053927/24b4aaa3-619b-454a-8164-b8d02cebbbbc
- Are the JIRAs under active …
> UIQM-547: Link Shared/Local MARC bib record to Shared/Local Authority record.

- CHANGELOG.md
- src/QuickMarcEditor/QuickMarcEditorRows/LinkButton/LinkButton.js
- src/QuickMarcEditor/QuickMarcEditorRows/LinkButton/LinkButton.test.js
- src/common/constants/filters.js
Hide the Shared facet in the plugin for the shared bib record.
https://github.com/folio-org/ui-plugin-find-authority/pull/76
https://github.com/folio-org/stripes-authority-components/pull/103
[UIQM-552](https://issues.folio.org/browse/UIQM-552)
https://github.com/folio-org/ui-quick-marc/assets/77053927/268ebfd8-e564-47c9-a1f4-a84850ea9891
Ideally all of …
> UIQM-552: Hide the Shared facet in the plugin for the shared bib record.

- src/QuickMarcEditor/QuickMarcEditorRows/LinkButton/LinkButton.js
- src/QuickMarcEditor/QuickMarcEditorRows/LinkButton/LinkButton.test.js
- src/QuickMarcEditor/QuickMarcEditorRows/QuickMarcEditorRows.js
- test/jest/__mock__/stripesCore.mock.js
https://issues.folio.org/browse/UIPFAUTH-76?focusedCommentId=182076&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-182076
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as …
> UIQM-547: Revise manual linking for tenants.

- src/MarcRoute/MarcRoute.js
- src/QuickMarcEditor/AutoLinkingButton/AutoLinkingButton.js
- src/QuickMarcEditor/QuickMarcCreateWrapper.js
- src/QuickMarcEditor/QuickMarcCreateWrapper.test.js
- src/QuickMarcEditor/QuickMarcDeriveWrapper.js
- src/QuickMarcEditor/QuickMarcDeriveWrapper.test.js
- src/QuickMarcEditor/QuickMarcEditWrapper.js
- src/QuickMarcEditor/QuickMarcEditWrapper.test.js
- src/QuickMarcEditor/QuickMarcEditor.js
- src/QuickMarcEditor/QuickMarcEditorContainer.js
- src/QuickMarcEditor/QuickMarcEditorRows/QuickMarcEditorRows.js
- src/QuickMarcEditor/utils.js
- src/hooks/useAuthorityLinking/useAuthorityLinking.js
- src/hooks/useAuthorityLinking/useAuthorityLinking.test.js
- src/queries/useAuthorityLinkingRules/useAuthorityLinkingRules.js
- src/queries/useAuthorityLinksCount/useAuthorityLinksCount.js
- src/queries/useAuthoritySourceFiles/useAuthoritySourceFiles.js
- src/queries/useLinkSuggestions/useLinkSuggestions.js
- src/queries/useMarcRecordMutation/useMarcRecordMutation.js
Fix tenant linking.
https://issues.folio.org/browse/UIPFAUTH-76?focusedCommentId=182258&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-182258
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be …
> UIQM-547: Fix tenant linking.

- CHANGELOG.md
- src/MarcRoute/MarcRoute.js
- src/QuickMarcEditor/QuickMarcEditorContainer.js
- src/QuickMarcEditor/QuickMarcEditorRows/LocationField/LocationField.js
- src/QuickMarcEditor/QuickMarcEditorRows/QuickMarcEditorRows.js
- src/QuickMarcEditor/utils.js
- src/hooks/useAuthorityLinking/useAuthorityLinking.js
Edit Shared MARC authority record, update Shared & Local Instances
[UIQM-556](https://issues.folio.org/browse/UIQM-556)
https://github.com/folio-org/ui-marc-authorities/pull/312
> UIQM-556 Edit Shared MARC authority record, update Shared & Local Instances

- CHANGELOG.md
- src/QuickMarcEditor/QuickMarcEditorRows/LocationField/LocationField.js
- src/QuickMarcEditor/QuickMarcEditorRows/utils.test.js
Allow a user to select a location code from the plugin.
[UIQM-528](https://issues.folio.org/browse/UIQM-528)
https://github.com/folio-org/ui-quick-marc/assets/77053927/614394c7-51b3-4492-84db-094442d56405 …
> UIQM-528: Allow a user to select a location code from the plugin.

- CHANGELOG.md
- package.json
Hide permission `quickMARC: Create a new MARC authority record`
[UIQM-564](https://issues.folio.org/browse/UIQM-564)
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and …
> UIQM-564: Hide permission 'quickMARC: Create a new MARC authority record'

- CHANGELOG.md
- package.json
Add marc-specifications to interfaces.
[UIQM-567](https://issues.folio.org/browse/UIQM-567) …
> UIQM-567: Add marc-specifications to interfaces.

- CHANGELOG.md
- src/QuickMarcEditor/QuickMarcEditWrapper.test.js
- src/QuickMarcEditor/QuickMarcEditor.js
- src/QuickMarcEditor/utils.js
Show correct message if record not found.
[UIQM-582](https://issues.folio.org/browse/UIQM-582)
https://github.com/folio-org/ui-quick-marc/assets/77053927/4bd5bfe2-ac76-4c7e-83a5-1dcb7b3867b7
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if …
> UIQM-582: Show correct message if record not found.

- CHANGELOG.md
- package.json
Add `authority-source-files` interface.
https://github.com/folio-org/mod-entities-links/pull/198
[UIQM-594](https://issues.folio.org/browse/UIQM-594)
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the …
> UIQM-594: Add authority-source-files interface.

- CHANGELOG.md
- src/QuickMarcEditor/QuickMarcEditorRows/LinkButton/LinkButton.js
- src/QuickMarcEditor/QuickMarcEditorRows/LinkButton/LinkButton.test.js
Build initial values for the `ui-find-authority` plugin using `EXACT_PHRASE` when there is $0 value due to recent changes in the advanced search.
[UIQM-597](https://issues.folio.org/browse/UIQM-597)
https://github.com/folio-org/ui-quick-marc/assets/77053927/1d48688a-5fae-4c6e-aabe-be3037cc971b
Ideally all of the PRs involved in breaking changes would be …
> UIQM-597: Build initial values for the find-authority plugin using EXACT_PHRASE when there is $0 value.

- CHANGELOG.md
- src/QuickMarcEditor/QuickMarcEditor.js
Not change the pane header of the authority record while editing the 1xx field.
[UIQM-555](https://issues.folio.org/browse/UIQM-555)
https://github.com/folio-org/ui-quick-marc/assets/77053927/668a29bb-84d0-414d-9ab0-02c00c20c8a3 …
> UIQM-555: Not change the pane header of the authority record while editing the 1xx field.

- .github/workflows/build-npm-release.yml
- .github/workflows/build-npm.yml
use `sonarsource/sonarcloud-github-action` from `master` to have the latest version.
While …
> use sonarsource/sonarcloud-github-action from master

- package.json
Follow-up.
Add `inventory-storage.authority-source-files.hrid.post` permission to create `hrid` when a user selects a local authority file.
https://github.com/folio-org/ui-marc-authorities/pull/357
[UIQM-576](https://issues.folio.org/browse/UIQM-576) …
> UIQM-576: Add `inventory-storage.authority-source-files.hrid.post` permission to create `hrid` when a user selects a local authority file.

- src/hooks/useValidation/rules.js
- src/hooks/useValidation/useValidation.test.js
Consider all prefix letters in 010 $a subfield.
[UIQM-577](https://issues.folio.org/browse/UIQM-577)
https://github.com/folio-org/ui-quick-marc/assets/77053927/8cb9b777-4ca3-43e0-9a58-c8829ab64583
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount …
> UIQM-577: Consider all prefix letters in 010 '$'a subfield.

- CHANGELOG.md
- src/QuickMarcEditor/QuickMarcCreateWrapper.js
- src/QuickMarcEditor/QuickMarcCreateWrapper.test.js
- src/QuickMarcEditor/QuickMarcEditorContainer.js
Wait for a redirect in the onSubmit function after creating a record.
[UIQM-607](https://folio-org.atlassian.net/browse/UIQM-607)
https://github.com/folio-org/ui-quick-marc/assets/77053927/b520e176-3fe4-4b99-9f11-4c75c16b4e55
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment. …
> UIQM-607: Wait for a redirect in the onSubmit function after creating a record.

- CHANGELOG.md
- src/QuickMarcEditor/QuickMarcEditor.js
- src/QuickMarcEditor/QuickMarcEditor.test.js
- test/jest/__mock__/stripesCore.mock.js
Add `shared` text to the title when editing a shared authority record.
[UIQM-627](https://folio-org.atlassian.net/browse/UIQM-627)
https://github.com/folio-org/ui-quick-marc/assets/77053927/c21d88d6-c373-46d5-aeac-005efbb78b24 …
> UIQM-627: Add `shared` text to the title when editing a shared authority record.

- CHANGELOG.md
- package.json
- src/QuickMarcEditor/QuickMarcCreateWrapper.test.js
- src/QuickMarcEditor/QuickMarcDeriveWrapper.js
- src/QuickMarcEditor/QuickMarcDeriveWrapper.test.js
- src/QuickMarcEditor/QuickMarcEditWrapper.js
- src/QuickMarcEditor/QuickMarcEditWrapper.test.js
- test/mocks/fixedFieldSpecBib.js
The `cleanBytesFields` function was not called with all required arguments. As a result, 008 field was saved with its initial values.
[UIQM-641](https://folio-org.atlassian.net/browse/UIQM-641)
https://github.com/folio-org/ui-quick-marc/assets/77053927/69b4a9b8-b41f-448d-8e6d-c96e14c70106
Ideally all of the PRs involved in breaking changes would be merged …
> UIQM-641: Call cleanBytesFields function with correct arguments to fix 008 field.

- CHANGELOG.md
- src/queries/useAuthoritySourceFiles/useAuthoritySourceFiles.js
- src/queries/useAuthoritySourceFiles/useAuthoritySourceFiles.test.js
Add `sortby` parameter to authority source files request
**Snapshot**
**With fix**
[UIQM-640](https://folio-org.atlassian.net/browse/UIQM-640)
> UIQM-640 Create authority | Make list of authority files in lookup alphabetical

- CHANGELOG.md
> Release v8.0.1

- CHANGELOG.md
- src/QuickMarcEditor/QuickMarcEditorRows/BytesField/BytesField.js
Add a `required` property to `Select` type fields so that screen readers read them as "required".
[UIQM-655](https://folio-org.atlassian.net/browse/UIQM-655)
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially …
> UIQM-655: Add a 'required' property to 'Select' type fields for screen readers.

- CHANGELOG.md
- src/QuickMarcEditor/QuickMarcEditorRows/LocationField/LocationField.js
Fix an accessibility issue by adding `aria-label` to the location field.
[UIQM-648](https://folio-org.atlassian.net/browse/UIQM-648)
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of …
> UIQM-648: Add aria-label to the location field.

- src/QuickMarcEditor/QuickMarcEditorRows/QuickMarcEditorRows.js
- src/QuickMarcEditor/QuickMarcEditorRows/SearchLink/SearchLink.js
- src/QuickMarcEditor/QuickMarcEditorRows/SearchLink/SearchLink.test.js
Change search link to MARC Authorities app for Authorities records
[UIQM-660](https://folio-org.atlassian.net/browse/UIQM-660)
> UIQM-660 Authority records should be searched in Authorities app (follow-up)

- CHANGELOG.md
- src/QuickMarcEditor/QuickMarcEditorRows/BytesField/BytesField.js
- src/QuickMarcEditor/QuickMarcEditorRows/LeaderField/LeaderField.js
- src/QuickMarcEditor/QuickMarcEditorRows/LeaderField/LeaderField.test.js
- src/QuickMarcEditor/QuickMarcEditorRows/LeaderField/leaderConfig.js
- src/QuickMarcEditor/QuickMarcEditorRows/QuickMarcEditorRows.js
Make leader positions `Type` and `BLvl` required when creating a bib record.
[UIQM-666](https://folio-org.atlassian.net/browse/UIQM-666)
Added `required` field for  `Type` and `BLvl` positions of `SELECT` type field. 
https://github.com/folio-org/ui-quick-marc/assets/77053927/97e55f1d-23ed-4134-b2d7-b1fc9f82e0e9
Ideally all of the PRs involved in breaking …
> UIQM-666: Make leader positions `Type` and `BLvl` required when creating a bib record.

- CHANGELOG.md
- src/QuickMarcEditor/QuickMarcEditorRows/SearchLink/SearchLink.js
- src/QuickMarcEditor/QuickMarcEditorRows/SearchLink/SearchLink.test.js
- translations/ui-quick-marc/en.json
Add a tooltip for the search link.
[UIQM-672](https://folio-org.atlassian.net/browse/UIQM-672)
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies …
> UIQM-672: Add a tooltip for the search link.

- src/QuickMarcEditor/QuickMarcEditorRows/ErrorMessages/ErrorMessages.css
- src/QuickMarcEditor/QuickMarcEditorRows/ErrorMessages/ErrorMessages.js
- src/hooks/useFocusFirstFieldWithError/useFocusFirstFieldWithError.js
Display all error messages in red
Wrap long error messages to next line
Fix focus shifts to MARC when editing a field
> UIQM-669 Fix displays of inline validation error messages (follow-up)

- src/hooks/useLccnDuplicationCheck/useLccnDuplicationCheck.js
- src/hooks/useLccnDuplicationCheck/useLccnDuplicationCheck.test.js
Search for bib record in all sources.
[UIQM-658](https://folio-org.atlassian.net/browse/UIQM-658)
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies …
> UIQM-658: Remove source restriction when searching for bib record by lccn.

- src/hooks/useValidation/useValidation.js
- src/hooks/useValidation/useValidation.test.js
Display LCCN error with `Fail`.
Add severity using `formatFEValidation`.
While it's helpful …
> UIQM-631: Format `lccnDuplicationError` using `formatFEValidation` to have severity.

- src/hooks/useLccnDuplicationCheck/useLccnDuplicationCheck.js
- src/hooks/useLccnDuplicationCheck/useLccnDuplicationCheck.test.js
Show an inline message if it is duplicated.
https://folio-org.atlassian.net/browse/UIQM-631
https://github.com/user-attachments/assets/40632815-5a42-482e-97d0-88c06e4caea9
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be …
> UIQM-631: Put LCCN message id into array (follow-up).

- translations/ui-quick-marc/en.json
Added a lost translation
[UIQM-656](https://folio-org.atlassian.net/browse/UIQM-656)
> UIQM-656 Added missing translation (follow-up)

- src/QuickMarcEditor/QuickMarcEditor.js
- src/QuickMarcEditor/QuickMarcEditor.test.js
- src/QuickMarcEditor/utils.js
- src/QuickMarcEditor/utils.test.js
- src/hooks/useAuthorityLinking/useAuthorityLinking.test.js
- src/hooks/useValidation/useValidation.js
- translations/ui-quick-marc/en.json
Close the validation modal window if an error occurs upun the validation process.
[UIQM-632](https://folio-org.atlassian.net/browse/UIQM-632)
Wrap the validation function in try-catch statement. 
Add `+` to the tag match to honor more than 10 errors for the same tag. 
https://github.com/user-attachments/assets/1500274a-4ab9-474b-8b85-c842c4a0a735
Ideally …
> UIQM-632: Consider more than 10 errors in backend validation for the same tag. Close the validation modal if an error occurs.

- CHANGELOG.md
- src/hooks/useValidation/rules.js
- src/hooks/useValidation/useValidation.test.js
Return removed UI validation in "quickmarc"
[UIQM-686](https://folio-org.atlassian.net/browse/UIQM-686)
> UIQM-686 Return removed UI validation in quickmarc

- CHANGELOG.md
- src/QuickMarcEditor/QuickMarcEditWrapper.js
Match payload formatting for submit and validate when editing.
https://github.com/user-attachments/assets/26578e14-7aca-4c9a-83fa-7eb494e956cb
[UIQM-690](https://folio-org.atlassian.net/browse/UIQM-690)
> UIQM-690 Match payload formatting for submit and validate when editing.

- CHANGELOG.md
- package.json
Upgrade `marc-records-editor` to 6.0
[UIQM-706](https://folio-org.atlassian.net/browse/UIQM-706)
> UIQM-706 Upgrade `marc-records-editor` to 6.0

- CHANGELOG.md
- package.json
- src/QuickMarc.js
- src/QuickMarcEditor/AutoLinkingButton/AutoLinkingButton.js
- src/QuickMarcEditor/QuickMarcEditor.js
- src/QuickMarcEditor/utils.js
- src/queries/useLccnDuplicateConfig/useLccnDuplicateConfig.js
- translations/ui-quick-marc/en.json
Rename permissions to match the naming [convention](https://folio-org.atlassian.net/wiki/spaces/FOLIJET/pages/156368925/Permissions+naming+convention). Remove [permissions violations](https://folio-org.atlassian.net/wiki/spaces/FOLIJET/pages/458752012/Permissions+violations) of this module.
Merge this PR with:
https://github.com/folio-org/ui-inventory/pull/2653
https://github.com/folio-org/stripes-testing/pull/4417
https://folio-org.atlassian.net/browse/UIQM-723
- Do JIRAs exist …
> UIQM-723: Update permissions.

- CHANGELOG.md
> Release v8.0.2

- CHANGELOG.md
- package.json
migrate stripes deps and react-intl to sunflower
[UIQM-751](https://folio-org.atlassian.net/browse/UIQM-751)
[UIQM-752](https://folio-org.atlassian.net/browse/UIQM-752)
> migrate stripes deps and react-intl to sunflower

- CHANGELOG.md
- package.json
Users with the `quickMARC: View MARC bibliographic record` permission should see the `Version history` pane.
[UIQM-761](https://folio-org.atlassian.net/browse/UIQM-761)
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, …
> UIQM-761: Add `audit.config.groups.settings.collection.get` permission for `quickMARC: View MARC bibliographic record`.

- package.json
> UIQM-761: Add permission `audit.config.groups.settings.audit.inventory.collection.get` to `quickMARC: View MARC bibliographic record` (follow-up).

- CHANGELOG.md
- translations/ui-quick-marc/en.json
Remove `Create a` text from the paneheader when creating new authority, bib, and holdings records. Make “Holdings” lowercase (“holdings”).
[UIQM-744](https://folio-org.atlassian.net/browse/UIQM-744) …
> UIQM-744: Remove `Create a` text from the paneheader when creating new authority, bib, and holdings records.
