CHANGELOG.md
src/QuickMarcEditor/QuickMarcEditorRows/utils.js
src/QuickMarcEditor/QuickMarcEditorRows/utils.test.js

UIQM-61 005 should not be an editable field
The 005 field is a system-generated field, it is a [Date and Time of Latest Transaction](https://www.loc.gov/marc/bibliographic/bd005.html).
Users should not be allowed to manually edit it.
The field in the form is made read-only
Maybe we should not pass the 005 field (and all other read-only fields) in the update request too.
Because making it read-only in the form gives no guarantee it can not be changed (using dev-tools in browser, for example).
But for now this won't work correctly: the PUT request takes the record in full, and if the field is not in it -it's being removed on server
- Does …

UIQM-61 005 should not be an editable field

---

CHANGELOG.md
src/QuickMarcEditor/QuickMarcRecordInfo/QuickMarcRecordInfo.css
src/QuickMarcEditor/QuickMarcRecordInfo/QuickMarcRecordInfo.js
src/QuickMarcEditor/QuickMarcRecordInfo/QuickMarcRecordInfo.test.js
src/QuickMarcEditor/QuickMarcRecordInfo/constants.js
translations/ui-quick-marc/en.json

Update record status displaying.
Issue [UIQM-67](https://issues.folio.org/browse/UIQM-67) …

UIQM-67: Update display of record status in quickMARC

---

CHANGELOG.md
package.json
src/QuickMarcEditor/QuickMarcEditor.js
src/QuickMarcEditor/QuickMarcEditorRows/BytesField/BytesField.js
src/QuickMarcEditor/QuickMarcEditorRows/IndicatorField/IndicatorField.js
src/QuickMarcEditor/QuickMarcEditorRows/QuickMarcEditorRows.css
src/QuickMarcEditor/QuickMarcEditorRows/QuickMarcEditorRows.js
src/QuickMarcEditor/QuickMarcEditorRows/QuickMarcEditorRows.test.js
src/common/constants/index.js
src/common/constants/restrictions.js
translations/ui-quick-marc/en.json
translations/ui-quick-marc/zh_CN.json

Change delete row behavior - remove deleting modal on each delete action, but show confirmation modal after clicking `Save and close` button.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of …

UIQM-72: Change delete row behavior

---

translations/ui-quick-marc/en.json

Fix translation message in the Delete modal.
Related issue: [UIQM-72](https://issues.folio.org/browse/UIQM-72) (updated in comments)

UIQM-72: Fix translation message

---

CHANGELOG.md
src/QuickMarcEditor/QuickMarcEditor.js
src/QuickMarcEditor/QuickMarcEditor.test.js
src/QuickMarcEditor/QuickMarcEditorRows/QuickMarcEditorRows.js
src/QuickMarcEditor/QuickMarcEditorRows/QuickMarcEditorRows.test.js
src/QuickMarcEditor/utils.js
src/QuickMarcEditor/utils.test.js

Change Delete field confirmation button behavior. Deleting rows and cancelling confirmation dialog will now restore deleted fields and keep other changes
[UIQM-76](https://issues.folio.org/browse/UIQM-76)

UIQM-76: Change Delete field confirmation [Cancel] button behavior

---

CHANGELOG.md
src/QuickMarcEditor/constants.js

Do not copy 035 and 019 fields content when deriving a new MARC record
[UIQM-78](https://issues.folio.org/browse/UIQM-78)

UIQM-78: Derive New MARC bibliographic record: Do not copy over 035 and 019 values

---

CHANGELOG.md
package.json
src/QuickMarcEditor/QuickMarcEditor.js

- Add missing status permission to Derive new MARC bib record permission
- Fix unresponsive Save&Close button after submit
[UIQM-89](https://issues.folio.org/browse/UIQM-89)

UIQM-89 Add missing status permission to Derive new MARC bib record permission

---

CHANGELOG.md
src/QuickMarcEditor/QuickMarcEditor.js
src/QuickMarcEditor/QuickMarcRecordInfo/QuickMarcRecordInfo.js
src/QuickMarcEditor/QuickMarcRecordInfo/QuickMarcRecordInfo.test.js
translations/ui-quick-marc/en.json

Add source label in pane sub title component for Edit Page
Issue: [UIQM-94](https://issues.folio.org/browse/UIQM-94)
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and …

UIQM-94: Display person who last edited quickMARC record

---

CHANGELOG.md
src/QuickMarcEditor/constants.js
src/QuickMarcEditor/utils.test.js

- Add field 003 to `FIELDS_TAGS_WITHOUT_DEFAULT_SUBFIELDS` constant
Issue: [UIQM-102](https://issues.folio.org/browse/UIQM-102)
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule …

UIQM-102: Do not auto-populate the 003 field with a leading $a

---

CHANGELOG.md
src/QuickMarcEditor/utils.js

Remove leading spaces at the beginning when adding MARC field during editing in quickMARC or deriving new MARC bib record.
[UIQM-128](https://issues.folio.org/browse/UIQM-128)

UIQM-128: Blank subfield created at beginning of MARC field when a whitespace is the leading character

---

CHANGELOG.md
src/QuickMarcEditor/QuickMarcDuplicateWrapper.js
src/QuickMarcEditor/QuickMarcEditWrapper.js
src/QuickMarcEditor/QuickMarcEditor.js

Disable Save&Close button when edit/duplicate quickMARC record request is pending.
When `onSubmit` handler is an async function you need to return a Promise to tell final-form if request is still in progress or not. Without this Save&Close button was not being disabled
[UIQM-133](https://issues.folio.org/browse/UIQM-133)

UIQM-133: Edit quikMARC/Derive quickMARC: Show a toast notification upon clicking Save & Close

---

src/QuickMarcEditor/utils.js
src/QuickMarcEditor/utils.test.js

Fix [PR](https://github.com/folio-org/ui-quick-marc/pull/195)
Issue: [UIQM-135](https://issues.folio.org/browse/UIQM-135)
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and …

UIQM-135: Fix validation for empty subfield

---

package.json

Depend on the new inventory interface version for optimistic locking -
in addition to the old interface version.
This modules uses GET only, it doesn't PUT to inventory.
Therefore no code change is needed to support the
_version property in these records that are needed for
optimistic locking.

UIQM-150: Add interface version for inventory optimistic locking

---

CHANGELOG.md
src/QuickMarcEditor/QuickMarcEditorRows/FixedField/HoldingsFixedField.js
translations/ui-quick-marc/en.json

Rename 008 `Rept date` field.
Issue: [UIQM-152](https://issues.folio.org/browse/UIQM-152) …

UIQM-152: Fix 008 Rept date field

---

CHANGELOG.md
src/QuickMarcEditor/QuickMarcRecordInfo/QuickMarcRecordInfo.js
src/QuickMarcEditor/QuickMarcRecordInfo/QuickMarcRecordInfo.test.js
translations/ui-quick-marc/en.json

Omit word 'Record' on Status and Last updated labels when Edit/Derive quickMARC.
Issue: [UIQM-177](https://issues.folio.org/browse/UIQM-177)

UIQM-177: Edit/Derive quickMARC > Omit Record on Status and Last updated labels

---

CHANGELOG.md
src/QuickMarcEditor/utils.js
src/QuickMarcEditor/utils.test.js
translations/ui-quick-marc/en.json

Do not allow user to add multiple 004s for MARC Holdings.
Issue: [UIQM-167](https://issues.folio.org/browse/UIQM-167)

UIQM-167: quickMARC - Holdings | Do not allow user to add multiple 004s

---

CHANGELOG.md
src/QuickMarcEditor/QuickMarcDuplicateWrapper.js
src/QuickMarcEditor/QuickMarcEditWrapper.js
src/QuickMarcEditor/utils.js
src/QuickMarcEditor/utils.test.js

Autopopulate an empty indicator box with a backslash when a value is missing in a box.
Issue: [UIQM-164](https://issues.folio.org/browse/UIQM-164)

UIQM-164: quickMARC : When a value is missing in an indicator box

---

.eslintrc
CHANGELOG.md
src/QuickMarcEditor/getQuickMarcRecordStatus.test.js
src/QuickMarcEditor/utils.js
src/QuickMarcEditor/utils.test.js
translations/ui-quick-marc/en.json

Update validation for MARC Holdings field with 852 tag
Issue: [UIQM-166](https://issues.folio.org/browse/UIQM-166) …

UIQM-166: Do not allow user to add 852s for MARC Holdings

---

CHANGELOG.md
src/QuickMarcEditor/constants.js
src/QuickMarcEditor/utils.js
src/QuickMarcEditor/utils.test.js

- Add 008 and 852 fields as a default for create MARC holdings record page
- Add tests
Issue: [UIQM-181](https://issues.folio.org/browse/UIQM-181)
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the …

UIQM-181: Add as a default 008 and 852 fields to create MARC Holdings record page

---

CHANGELOG.md
package.json
src/QuickMarcEditor/utils.js
src/QuickMarcEditor/utils.test.js

Use a supported version of `uuid` that doesn't throw build warnings.
Attn: @dmitriyfolio , @Vladyslav-Velytskyi 
Refs [UIQM-191](https://issues.folio.org/browse/UIQM-191)

UIQM-191 use supported uuid

---

CHANGELOG.md
package.json

The popular mock-data generation package 'faker' has been emptied by the maintainer... the latest, broken version is 6.6.6
Locking the version in case they empty older major versions

Lock faker version

---

CHANGELOG.md
src/QuickMarcView/QuickMarcView.js
src/QuickMarcView/QuickMarcView.test.js

Changes needed for MARC Authorities App: Closing third pane does not resize the second pane.
The wrapping Paneset around `QuickMarcView` component was preventing the result list pane from resizing properly when the detail view pane was closed in the MARC Authorities App. So the new prop `isPaneset` was introduced to indicate when that Paneset is not needed.
[UIQM-195](https://issues.folio.org/browse/UIQM-195)
Relates to: [UIMARCAUTH-37](https://issues.folio.org/browse/UIMARCAUTH-37)

UIQM-195: Changes for MARC Authorities App: Closing third pane does not resize the second pane

---

CHANGELOG.md
src/QuickMarcEditor/QuickMarcCreateWrapper.js

Prevent Instance record from showing when saving new MARC Holdings created via quickmark.
[UIQM-198](https://issues.folio.org/browse/UIQM-198)

UIQM-198: Saving a MARC holdings record upon creation/update displays Instance record then Holdings record

---

CHANGELOG.md
package.json

Reverting release commit for 5.0.0. Module was not released and we can safely remove this for now

Revert "Release v5.0.0 (#262)"

---

CHANGELOG.md
src/QuickMarcEditor/QuickMarcCreateWrapper.test.js
src/QuickMarcEditor/QuickMarcDuplicateWrapper.test.js
src/QuickMarcEditor/getQuickMarcRecordStatus.test.js
src/QuickMarcEditor/utils.js
src/QuickMarcEditor/utils.test.js

Fix MARC row is not saved when every subfield code in this row is not separated by space with its value (e.g. `$atesting $btestingtwo`).
It was happening due to regex in `checkIsEmptyContent` function which considered field content empty if all of its space separated parts started with `$` followed by zero to **unlimited** number of characters. This considered both `$atesting` and `$btestingtwo` parts as not holding any values.
What needed to be done is to alter regex to consider field content empty only if all of its space separated parts started with `$` followed by zero to **one** number of characters. Thus considering `$atesting` and `$btestingtwo` parts to have values but `$a` and `$b` to have empty values.
[UIQM-205](https://issues.folio.org/browse/UIQM-205)

UIQM-205: Improve handling of parsing multiple subfields

---

package.json

There are three builds in npm-folioci with version `5.0.1...` that prevent users from getting the latest builds of quickMARC because `5.0.0` > `4.0.3`. We need to increment the version to fix this
https://github.com/folio-org/ui-marc-authorities/pull/73
https://github.com/folio-org/ui-inventory/pull/1607

Increment version to next latest release (5.0.0)

---

CHANGELOG.md
package.json

Update `records-editor.records` interface version to v3.1.
[UIQM-214](https://issues.folio.org/browse/UIQM-214)

UIQM-214: Update 'records-editor.records' interface version

---

CHANGELOG.md
package.json
translations/ui-quick-marc/en.json

Added new permission: "View MARC holdings record"
[UIQM-213](https://issues.folio.org/browse/UIQM-213)
https://github.com/folio-org/ui-inventory/pull/1632

UIQM-213 New Permission: View MARC holdings record

---

CHANGELOG.md
src/QuickMarc.js
src/QuickMarcEditor/OptimisticLockingBanner/OptimisticLockingBanner.js
src/QuickMarcEditor/OptimisticLockingBanner/OptimisticLockingBanner.test.js
src/QuickMarcEditor/OptimisticLockingBanner/index.js
src/QuickMarcEditor/QuickMarcCreateWrapper.js
src/QuickMarcEditor/QuickMarcCreateWrapper.test.js
src/QuickMarcEditor/QuickMarcDuplicateWrapper.js
src/QuickMarcEditor/QuickMarcDuplicateWrapper.test.js
src/QuickMarcEditor/QuickMarcEditWrapper.js
src/QuickMarcEditor/QuickMarcEditWrapper.test.js
src/QuickMarcEditor/QuickMarcEditor.js
src/QuickMarcEditor/QuickMarcEditorContainer.js
src/QuickMarcEditor/utils.js
src/common/constants/errorTypes.js
src/common/constants/index.js

Showing optimistic locking banner when a user tries to update an old version of a record
[UIQM-162](https://issues.folio.org/browse/UIQM-162)
https://github.com/folio-org/ui-inventory/pull/1645

UIQM-162: Optimistic locking: display error message to inform user about OL

---

CHANGELOG.md
jest.config.js
src/QuickMarcEditor/QuickMarcEditor.js
src/QuickMarcEditor/QuickMarcEditorRows/LocationField/LocationField.js
src/QuickMarcEditor/QuickMarcEditorRows/LocationField/LocationField.test.js
src/QuickMarcEditor/QuickMarcEditorRows/QuickMarcEditorRows.js
src/QuickMarcEditor/utils.js

Fix issue with incorrect error displayed when saving a record with multiple 852 fields
There were two issues: with `<LocationField>` and `<QuickMarcEditorRows>`
1. `<LocationField>` accepted `permanentLocation` as a prop. This was stored higher in the component tree, so all location rows shared the same location. The fix is to store `permanentLocation` in state of `<LocationField>`
2. `<QuickMarcEditorRows>` used index as a key for rows. When deleting a row it caused some weird mixing of row contents.
https://user-images.githubusercontent.com/19309423/161759249-4be2d5b2-9935-471d-a0cb-08b3a878c048.mp4
[UIQM-226](https://issues.folio.org/browse/UIQM-226)

UIQM-226 MARC holdings: Can add multiple 852s tags

---

CHANGELOG.md
src/QuickMarcEditor/QuickMarcEditor.js
src/QuickMarcEditor/QuickMarcEditor.test.js

Fix Folio crashes in quickmarc editor when cypress clears LDR field
https://user-images.githubusercontent.com/19309423/171904831-22831c43-b20f-45af-89c0-4c24d4e5d42d.mp4
[UIQM-247](https://issues.folio.org/browse/UIQM-247)

UIQM-247 Folio crashes in quickmarc editor when cypress clears LDR field

---

CHANGELOG.md
src/QuickMarcEditor/constants.js

Add support for `\`, space and a non-breaking space in MARC Holdings Leader 18
[UIQM-267](https://issues.folio.org/browse/UIQM-267)

UIQM-267 MARC Holdings - Leader position 18 accept a space and \ as a valid value

---

CHANGELOG.md
src/QuickMarcEditor/QuickMarcEditorRows/QuickMarcEditorRows.js
src/QuickMarcEditor/QuickMarcEditorRows/QuickMarcEditorRows.test.js

- By clicking on Add a field the focus should shift to the newly added row's MARC tag text box
- By clicking on Remove a field the focus should move the next down row's MARC tag text box 
[UIQM-261](https://issues.folio.org/browse/UIQM-261)
https://user-images.githubusercontent.com/77053927/183629289-e201ee65-841c-4d7f-ad04-7b57b919481d.mp4
Ideally all of …

UIQM-261: Shift focus to MARC tag box once you click Add or Delete field

---

CHANGELOG.md
src/QuickMarcEditor/QuickMarcEditWrapper.js
src/QuickMarcEditor/QuickMarcEditor.js
src/QuickMarcEditor/QuickMarcEditorContainer.js
src/QuickMarcEditor/QuickMarcEditorRows/QuickMarcEditorRows.js
src/QuickMarcEditor/QuickMarcEditorRows/QuickMarcEditorRows.test.js
src/QuickMarcEditor/utils.js
src/QuickMarcEditor/utils.test.js

Restore deleted fields in the same position as it was.
Instead of removing deleted field from form state - it's now marked as `_isDeleted`, which allows to keep it's original index in fields array.
https://user-images.githubusercontent.com/19309423/184117990-c5cbe7d8-ef0c-43cb-99de-12ad8a3b4c14.mp4
[UIQM-266](https://issues.folio.org/browse/UIQM-266)

UIQM-266 Edit quickMARC: Undoing a delete field is not restored in the same position

---

CHANGELOG.md
src/QuickMarcEditor/QuickMarcEditorRows/ContentField/ContentField.js
src/QuickMarcEditor/QuickMarcEditorRows/QuickMarcEditorRows.js
src/QuickMarcEditor/QuickMarcEditorRows/QuickMarcEditorRows.test.js

After adding a new row, the subfield should be focused and the cursor needs to be at the end of the field value.
[UIQM-273](https://issues.folio.org/browse/UIQM-273)
https://user-images.githubusercontent.com/77053927/186637265-9a418201-815c-42ed-b054-b78c523ab08e.mp4
Ideally all of the PRs involved in breaking changes would be merged in the same day to …

UIQM-273: Add a new field : Default focus/cursor to after $a

---

CHANGELOG.md
package.json

Add version 12.0 to the list of supported inventory interface versions.
DELETE /inventory/instances and DELETE /inventory/items have been deleting all records.
MODINV-731 changed them to delete records by CQL, this requires a major interface version bump.
ui-quick-marc doesn't need any code change because it doesn't use these two DELETE APIs.

UIQM-285: Support inventory 12.0 in okapiInterfaces

---

CHANGELOG.md
src/QuickMarcEditor/QuickMarcEditorRows/QuickMarcEditorRows.css
src/QuickMarcEditor/QuickMarcEditorRows/QuickMarcEditorRows.js

Change field level actions display
Changed items order of `QuickMarcEditorRows`. Removed a fixed width from `quickMarcEditorActions` styles which was causing an extra space between `quickMarcEditorActions` items and `quickMarcEditorRowContent` item.
[UIQM-256](https://issues.folio.org/browse/UIQM-256)

UIQM-256: Change field level actions display

---

CHANGELOG.md
src/QuickMarcEditor/QuickMarcEditorRows/QuickMarcEditorRows.js

In the scenario that you cannot move up any further: If you hit the Enter key on the last up arrow then shift to that row's down arrow.
In the scenario that you cannot move down any further: If you hit the Enter key on the last down arrow then shift to that row's up arrow.
[UIQM-292](https://issues.folio.org/browse/UIQM-292)

UIQM-292: Change field level actions for Move field a row buttons.

---

src/hooks/useAuthorityLinking/useAuthorityLinking.js
src/hooks/useAuthorityLinking/useAuthorityLinking.test.js

Fix issue with repeated subfields being joined with `,`
https://user-images.githubusercontent.com/19309423/195117625-753d3fdc-26ce-4adf-b7cd-a5a0503ea4c0.mp4
[UIQM-275](https://issues.folio.org/browse/UIQM-275)

UIQM-275: Handle repeated subfields

---

package.json

Hide "Can Link/unlink authority records to bib records" permission
[UIQM-288](https://issues.folio.org/browse/UIQM-288)

UIQM-288 Hide link authority permission

---

CHANGELOG.md
src/QuickMarcEditor/QuickMarcEditorRows/BytesField/BytesField.js
src/QuickMarcEditor/QuickMarcEditorRows/QuickMarcEditorRows.js
src/QuickMarcEditor/QuickMarcEditorRows/QuickMarcEditorRows.test.js
src/hooks/useAuthorityLinking/useAuthorityLinking.js
src/hooks/useAuthorityLinking/useAuthorityLinking.test.js

Be able to link the bib field when the content of the field is empty.
[UIQM-317](https://issues.folio.org/browse/UIQM-317)
https://user-images.githubusercontent.com/77053927/199765027-408dced4-ae35-4580-8bc2-968846835728.mp4
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment. …

UIQM-317: Linking of empty field with "MARC Authority" record doesn't happen 

---

package.json

This permission is referenced in at least two other modules (ui-inventory and stripes-testing) so the permission name should be changed back
[UIQM-315](https://issues.folio.org/browse/UIQM-315)

UIQM-315: Rename derive bib record permission back to duplicate

---

package.json
src/QuickMarc.js
translations/ui-quick-marc/en.json

Keep Derive permission named as `duplicate` to prevent breaking changes to quick marc and other modules
[UIQM-315](https://issues.folio.org/browse/UIQM-315)

UIQM-315 Rename permission to duplicate, now will definitely work as expected

---

CHANGELOG.md
src/QuickMarcEditor/QuickMarcEditorContainer.js
src/QuickMarcEditor/QuickMarcEditorContainer.test.js

Always display the actual record version in the URL (`relatedRecordVersion`).
[UIIN-2244 pool request](https://github.com/folio-org/ui-inventory/pull/1846)
[UIQM-319](https://issues.folio.org/browse/UIQM-319)
[UIIN-2244](https://issues.folio.org/browse/UIIN-2244)
https://user-images.githubusercontent.com/77053927/201738117-231526c2-6734-46a9-b5f6-2e5797b78d61.mp4
- Do PRs exist for these …

UIQM-319: Not actual "relatedRecordVersion" value sends when user saves "MARC Bib" record

---

CHANGELOG.md
src/QuickMarcEditor/QuickMarcCreateWrapper.js
src/QuickMarcEditor/QuickMarcDuplicateWrapper.js

Instead of deleting fields we mark them as `_isDeleted` to be able to restore them in correct position
Remove fields marked as deleted from form values before saving
https://user-images.githubusercontent.com/19309423/200852428-b6e3fc19-ab37-40ef-9645-79d9f15e1652.mp4
[UIQM-321](https://issues.folio.org/browse/UIQM-321)

UIQM-321: Deleted fields not processing when deriving a new MARC bibliographic record

---

src/hooks/useAuthorityLinking/useAuthorityLinking.js

Fix validation for subfield existence
Using `&&` returns incorrect results when there's a rule `{ t: false }`. In all cases it will make linking invalid
Instead need to use `==` - that way we will check that existence of subfield and validation rule match
https://user-images.githubusercontent.com/19309423/206145465-6afdceea-b235-42ea-8a03-674515a16996.mp4
[UIQM-295](https://issues.folio.org/browse/UIQM-295)

UIQM-295 Fix validation for subfield existence

---

CHANGELOG.md
src/hooks/useAuthorityLinking/useAuthorityLinking.js
src/hooks/useAuthorityLinking/useAuthorityLinking.test.js

Use authority linking rules to provide correct list of controlled subfields
https://user-images.githubusercontent.com/19309423/208895928-afe15c56-8723-4c41-9887-4bed9e0e8cc4.mp4
[UIQM-339](https://issues.folio.org/browse/UIQM-339)

UIQM-339 Uncontrolled subfield moved to read only box when linked "MARC Authority" has the same subfield indicator

---

CHANGELOG.md
src/QuickMarcEditor/utils.js
src/QuickMarcEditor/utils.test.js
translations/ui-quick-marc/en.json

Similar to what was done with 001 field, we check to see if there are duplicate 010 fileds and display the corresponding error message.
https://user-images.githubusercontent.com/101110095/211549081-06a9ff80-81d4-4ecb-83b5-ef16c7af26ea.mp4
[UIQM-330](https://issues.folio.org/browse/UIQM-330)

UIQM-330: Forbid duplicate MARC010 fields

---

CHANGELOG.md
src/QuickMarcEditor/QuickMarcEditorRows/QuickMarcEditorRows.js
src/QuickMarcEditor/QuickMarcEditorRows/QuickMarcEditorRows.test.js

Fix Reference record displaying when opening linked record
We're opening unique Authorized record, so we can ignore `headingRef` param that can be inconsistently formatted
https://user-images.githubusercontent.com/19309423/211845762-ca1da83e-b56b-43a7-b3b2-6f33a1de39ec.mp4
[UIQM-353](https://issues.folio.org/browse/UIQM-353)
https://github.com/folio-org/stripes-authority-components/pull/52

UIQM-353 Don't pass headingRef to href to linked authority record

---

CHANGELOG.md
src/QuickMarcEditor/QuickMarcEditorRows/QuickMarcEditorRows.js
src/QuickMarcEditor/QuickMarcEditorRows/utils.js
src/QuickMarcEditor/QuickMarcEditorRows/utils.test.js

Disallowed users to delete 1XX field when editing MARC Authority records
[UIQM-345](https://issues.folio.org/browse/UIQM-345)

UIQM-345: Do not allow users to delete 1XX fields

---

CHANGELOG.md
package.json

Reverts folio-org/ui-quick-marc#429 until back-end interface has been updated

Revert "UIQM-349 Align the module with API breaking change"

---

CHANGELOG.md
src/QuickMarcEditor/QuickMarcEditorRows/utils.js
src/QuickMarcEditor/QuickMarcEditorRows/utils.test.js

Do not allow users po delete MARC bib 245 and MARC holdindins fields
[UIQM-343](https://issues.folio.org/browse/UIQM-343)
[UIQM-344](https://issues.folio.org/browse/UIQM-344)

UIQM-343: Do not allow users to delete MARC bib 245 and MARC holdindins fields

---

CHANGELOG.md
src/QuickMarcEditor/QuickMarcCreateWrapper.js
src/QuickMarcEditor/QuickMarcCreateWrapper.test.js
src/QuickMarcEditor/QuickMarcDeriveWrapper.js
src/QuickMarcEditor/QuickMarcDeriveWrapper.test.js
src/QuickMarcEditor/QuickMarcEditWrapper.js
src/QuickMarcEditor/QuickMarcEditor.js
src/QuickMarcEditor/QuickMarcEditor.test.js

Update handling form submit to validate record and show error messages first
https://user-images.githubusercontent.com/19309423/213450482-e532de09-a57f-4c3a-abb0-d0d5de1c537e.mp4
https://user-images.githubusercontent.com/19309423/213450700-5c2bc510-6c1b-4a0e-b80b-a646f3c67063.mp4
[UIQM-347](https://issues.folio.org/browse/UIQM-347)

UIQM-347 quickMARC | Show errors messages then show confirmation messages

---

CHANGELOG.md
src/hooks/useAuthorityLinking/useAuthorityLinking.js
src/hooks/useAuthorityLinking/useAuthorityLinking.test.js

Subfields that are in the linking rules but not in the authority should be removed.
[UIQM-337](https://issues.folio.org/browse/UIQM-337)
https://user-images.githubusercontent.com/77053927/213513370-26ad4d09-dc14-442e-8306-96c009cbda97.mp4 …

UIQM-337: Controlled subfield is displayed as not controlled after linking of MARC Bib field with MARC Authority

---

src/QuickMarcEditor/QuickMarcDeriveWrapper.js
src/QuickMarcEditor/QuickMarcEditWrapper.js
src/QuickMarcEditor/utils.js
src/QuickMarcEditor/utils.test.js
translations/ui-quick-marc/en.json

Show an error when entering $9
[UIQM-341](https://issues.folio.org/browse/UIQM-341?focusedCommentId=155410&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-155410)
https://user-images.githubusercontent.com/77053927/213707979-7100d8e1-d528-4457-a69e-ca35b5a034b4.mp4
Ideally all of the PRs involved in breaking changes would be …

UIQM-341: Show an error when entering '$'9

---

CHANGELOG.md
src/QuickMarcEditor/QuickMarcEditorRows/SplitField/SplitField.js

Enable save buttons only when there are changes.
[UIQM-373](https://issues.folio.org/browse/UIQM-373)
https://user-images.githubusercontent.com/77053927/214044178-5e0da8b7-81fc-4dfe-9205-fd2279fc73de.mp4 …

UIQM-373: Save buttons are not disabled after removing unsaved updates from linked field in "MARC bib" record

---

CHANGELOG.md
src/QuickMarcEditor/QuickMarcEditorRows/utils.js

is1XXField function in utils.js needs to check if the parameter is undefined instead of string before accessing its first character
https://user-images.githubusercontent.com/101110095/212901249-55f0333e-c0d9-44d7-8d13-61de8971d1d1.mp4
[UIQM-370](https://issues.folio.org/browse/UIQM-370)

UIQM-370: check for undefined parameter in  is1XXXField utility function

---

src/QuickMarcEditor/QuickMarcEditor.js

Fix delete fields and update links confirmations flow
Create a state object `confirmationChecks` which stores flag which confirmations need to be run
After a check has been confirmed - set it's flag to `false`. Need this to skip this check when running `confirmSubmit` again
Reset `confirmationChecks` when clicking on submit buttons or using `mod+s` shortcut
https://user-images.githubusercontent.com/19309423/214277355-2e853e34-55f9-4df3-ae38-0402ccd3816f.mp4
[UIQM-347](https://issues.folio.org/browse/UIQM-347)

UIQM-347 Fix delete fields and confirm update links flow

---

CHANGELOG.md
src/QuickMarcEditor/utils.js
src/QuickMarcEditor/utils.test.js
translations/ui-quick-marc/en.json

Show an error toast message when a user enters a subfield that can be controlled.
[UIQM-367](https://issues.folio.org/browse/UIQM-367)
https://user-images.githubusercontent.com/77053927/215699450-7c03db01-f101-4862-8f3f-ac9460a58cb7.mp4 …

UIQM-367: Show an error toast message when user enters a subfield that is/can be controlled by an authority record or is the linking match point

---

CHANGELOG.md
src/QuickMarcEditor/QuickMarcEditorRows/QuickMarcEditorRows.js
src/QuickMarcEditor/QuickMarcEditorRows/SplitField/SplitField.css
src/QuickMarcEditor/QuickMarcEditorRows/SplitField/SplitField.js
src/QuickMarcEditor/QuickMarcEditorRows/SplitField/SplitField.test.js

Allow linked fields to be resized
https://user-images.githubusercontent.com/19309423/215756983-977d4bb0-3a1c-4a51-b5d6-fc4286cafb9f.mp4
[UIQM-385](https://issues.folio.org/browse/UIQM-385)
https://github.com/folio-org/stripes-components/pull/1976

UIQM-385 Edit/Derive quickMARC | Allow user to drag text boxes to view all content

---

src/QuickMarcEditor/QuickMarcEditWrapper.test.js
src/QuickMarcEditor/QuickMarcEditor.js
src/QuickMarcEditor/utils.js
src/QuickMarcEditor/utils.test.js
src/hooks/useAuthorityLinking/useAuthorityLinking.js

- Forbid creation of field 010 $a when 001 is linked and 010 is absent.
- Revise the `getContentSubfieldValue` to return an array of subfields instead of a string.
[UIQM-386](https://issues.folio.org/browse/UIQM-386?focusedCommentId=157307&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-157307)
https://user-images.githubusercontent.com/77053927/217550769-b3002b71-7a9c-478a-90c4-2468a48287ce.mp4
- …

UIQM-386: Forbid creation of field 010 $a when 001 is linked and 010 is absent.

---

src/QuickMarcEditor/utils.js
src/QuickMarcEditor/utils.test.js
translations/ui-quick-marc/en.json

Remove the ability to delete field 010 and subfield 010 $a when 010 is linked.
[UIQM-348 comment 1](https://issues.folio.org/browse/UIQM-348?focusedCommentId=157538&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-157538)
[UIQM-348 comment 2](https://issues.folio.org/browse/UIQM-348?focusedCommentId=157597&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-157597)
https://user-images.githubusercontent.com/77053927/217619550-807c4d6c-3639-4735-b221-da490deb5f1f.mp4
- …

UIQM-348: Remove the ability to delete field 010 and subfield 010 $a when 010 is linked

---

CHANGELOG.md
src/QuickMarcView/PrintPopup/PrintPopup.js
src/QuickMarcView/PrintPopup/PrintPopup.test.js
src/QuickMarcView/QuickMarcView.js
src/QuickMarcView/QuickMarcView.test.js

Remove the print button from this plugin to make it more flexible.
This changes affects:
https://github.com/folio-org/ui-inventory/pull/1988
https://github.com/folio-org/ui-marc-authorities/pull/242
[UIQM-351](https://issues.folio.org/browse/UIQM-351)
Need to merge simultaneously with https://github.com/folio-org/ui-inventory/pull/1988
Ideally all of the …

UIQM 351: MARC Authority | Print Source record

---

CHANGELOG.md
src/QuickMarcEditor/constants.js

Add support for values 'b' and 'c' in Bib Leader/19
[UIQM-410](https://issues.folio.org/browse/UIQM-410)

UIQM-410 FE - Edit/Derive a MARC bib - Returns an error when MARC LDR_19 value is 'b' or 'c'

---

CHANGELOG.md
package.json

Added missing permission to get linking rules to display MARC Authority links
[UIQM-445](https://issues.folio.org/browse/UIQM-445)

UIQM-445 Fix missing permission to view MARC Authority icon in MARC bib source view

---

CHANGELOG.md
translations/ui-quick-marc/en.json

MARC field number isn't highlighted in bold in "Unlink from MARC authority record" modal
[UIQM-412](https://issues.folio.org/browse/UIQM-412)

UIQM-412 Fix translation format

---

.github/workflows/build-npm-release.yml
.github/workflows/build-npm.yml

Use `sonarcloud-github-action v1.8` that doesn't require Node >=14

Use sonarcloud-github-action v1.8 to fix error with incorrect node version

---

CHANGELOG.md
src/hooks/useAuthorityLinking/useAuthorityLinking.js
src/hooks/useAuthorityLinking/useAuthorityLinking.test.js

Always replace `$0` with authority's `naturalId`
https://user-images.githubusercontent.com/19309423/234007571-8bebe2e4-298a-429b-b56c-32406d28f423.mp4
[UIQM-457](https://issues.folio.org/browse/UIQM-457)

UIQM-457 "Base URL" doesn't add to linked field when "$0" exactly matches with "naturalId"

---

src/QuickMarcEditor/QuickMarcCreateWrapper.js
src/QuickMarcEditor/QuickMarcDeriveWrapper.js
src/QuickMarcEditor/QuickMarcEditWrapper.js

Fix flow of preparation of marc record for save - no need to use `map` and can just pass a function
[UIQM-448](https://issues.folio.org/browse/UIQM-448)

UIQM-448 Fix marc record preparation for save flow

---

CHANGELOG.md
src/QuickMarcEditor/constants.js
src/QuickMarcEditor/utils.js
src/QuickMarcEditor/utils.test.js
translations/ui-quick-marc/en.json

Make Leader validation error message consistent for all MARC types.
https://github.com/folio-org/ui-quick-marc/assets/19309423/1c492540-2fc9-441c-926e-7be91c65ea04
[UIQM-419](https://issues.folio.org/browse/UIQM-419)

UIQM-419 Make Leader validation error message consistent for all MARC types.

---

CHANGELOG.md
src/QuickMarcEditor/QuickMarcEditor.js
src/QuickMarcEditor/QuickMarcEditorRows/QuickMarcEditorRows.js
src/QuickMarcEditor/QuickMarcEditorRows/QuickMarcEditorRows.test.js
src/QuickMarcEditor/utils.js

Listen to field tag change events and save content to new `_fieldTypeSwapContent` property.
When changing from 00X to content fields - save old content and set content to empty string
https://github.com/folio-org/ui-quick-marc/assets/19309423/2f7745ff-1c9d-4f30-9265-cc82a088ab3c
[UIQM-492](https://issues.folio.org/browse/UIQM-492)

UIQM-492 Fix error when changing field type from 00X to content and vice versa.

---

src/QuickMarcEditor/QuickMarcEditorRows/QuickMarcEditorRows.js
src/QuickMarcEditor/QuickMarcEditorRows/QuickMarcEditorRows.test.js

Fix issue where changed tag value was not saved to form state and caused validation error
https://github.com/folio-org/ui-quick-marc/assets/19309423/69b0e544-e1e1-4500-8192-a23c6075379f
[UIQM-492](https://issues.folio.org/browse/UIQM-492)

UIQM-492 Fix issue with tag value not changing in form state

---

src/QuickMarcEditor/utils.js
src/hooks/useAuthorityLinking/useAuthorityLinking.js
src/hooks/useAuthorityLinking/useAuthorityLinking.test.js

Take uncontrolled subfields from the current field, not from suggested one.
https://github.com/folio-org/ui-quick-marc/assets/77053927/3073d391-9ef8-4c5c-81d8-258a4ebe2388
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be …

UIQM-326: Take uncontrolled subfields from the current field, not from suggested one.

---

CHANGELOG.md
src/QuickMarcEditor/QuickMarcCreateWrapper.js

Autopopulate subfields when Creating MARC records.
https://github.com/folio-org/ui-quick-marc/assets/19309423/bc04845e-deff-4d0d-a8b9-56ab1fe3d732
[UIQM-509](https://issues.folio.org/browse/UIQM-509)

UIQM-509: Autopopulate subfields when Creating MARC records.

---

CHANGELOG.md
src/QuickMarcView/MarcContent/MarcContent.js
src/QuickMarcView/MarcField.js
src/QuickMarcView/QuickMarcView.js

Change tenant id to central when opening details of Shared Authority
[UIQM-545](https://issues.folio.org/browse/UIQM-545)
https://github.com/folio-org/ui-plugin-find-authority/pull/74
https://github.com/folio-org/stripes-authority-components/pull/99
https://github.com/folio-org/ui-marc-authorities/pull/306

UIQM-545  Change tenant id to central when opening details of Shared Authority

---

CHANGELOG.md
src/QuickMarcEditor/QuickMarcDeriveWrapper.js
src/QuickMarcEditor/QuickMarcDeriveWrapper.test.js
src/QuickMarcEditor/QuickMarcEditorContainer.js

Previously, when saving a derived record, the `shared` url parameter was not removed due to using custom behavior on close, not from `ui-inventory`. And if the record is opened again, and it is local, the request was with central tenant, which is wrong and the record could not be found.
Use `onClose` prop from `ui-inventory` when a derived record is saved to have one source of truth to remove unnecessary params.
[UIQM-550](https://issues.folio.org/browse/UIQM-550)
https://github.com/folio-org/ui-inventory/pull/2249
https://github.com/folio-org/ui-quick-marc/assets/77053927/c9c78015-192d-4957-ba6c-0ef8e30f2753
- Does this introduce …

UIQM-550: Use onClose prop when a derived record is saved to have one source of truth to remove unnecessary params.

---

CHANGELOG.md
src/QuickMarcEditor/QuickMarcEditor.js
src/QuickMarcEditor/QuickMarcEditor.test.js

Do not pass the `event` to the `onClose` callback.
[UIQM-554](https://issues.folio.org/browse/UIQM-554)
https://github.com/folio-org/ui-quick-marc/assets/77053927/5ac84c1b-65f4-4699-86a2-2d5e0567b65d …

UIQM-554: Don't pass any arguments to the onClose callback when clicking the Cancel panel button.

---

CHANGELOG.md
src/QuickMarcEditor/QuickMarcEditorRows/utils.js
src/QuickMarcEditor/QuickMarcEditorRows/utils.test.js

Create/Edit/Derive MARC bib/holdings/authority - Allow a user to move 00X fields
https://github.com/folio-org/ui-quick-marc/assets/19309423/14e01444-9e17-4796-b579-c12cdd15fde0
[UIQM-530](https://issues.folio.org/browse/UIQM-530)

UIQM-530 Create/Edit/Derive MARC bib/holdings/authority - Allow a user to move 00X fields

---

CHANGELOG.md
src/QuickMarcEditor/AutoLinkingButton/AutoLinkingButton.js
src/QuickMarcEditor/AutoLinkingButton/AutoLinkingButton.test.js
src/QuickMarcEditor/QuickMarcEditor.js
src/QuickMarcEditor/utils.js
src/hooks/useAuthorityLinking/useAuthorityLinking.js
src/hooks/useAuthorityLinking/useAuthorityLinking.test.js

Make auto-linking for the consortium.
Consolidate common functionality of auto-linking and actualization of links.
Create a `getSuggestedFields` function that fetches link suggestions from the member and/or central tenants. 
[UIQM-559](https://issues.folio.org/browse/UIQM-559)
Ocasionally `/link/suggestions` doesn't return the suggested field when it should. This is a known issue and there is a BE ticket for this ([MODELINKS-118](https://issues.folio.org/browse/MODELINKS-118)).
https://github.com/folio-org/ui-quick-marc/assets/77053927/8be2163f-6b10-4428-872d-27814a0864d1
If there are breaking …

UIQM-559: Make auto-linking for the consortium.

---

CHANGELOG.md
src/QuickMarcEditor/QuickMarcEditWrapper.js
src/QuickMarcEditor/QuickMarcEditWrapper.test.js

Fix issue with handling `0` version of MARC records
https://github.com/folio-org/ui-quick-marc/assets/19309423/462dd587-7351-454c-8dc6-b2d91472c6fa
[UIQM-562](https://issues.folio.org/browse/UIQM-562)

UIQM-562 Optimistic locking error doesn't appear when edit "MARC authority" record

---

package.json

Fix by add permissions to marc-specifications endpoint

UIQM-431 fix

---

CHANGELOG.md
package.json

Added `marc-records-editor.item.put` to Derive Bib permission to fix issue with broken links after deriving a record.
[UIQM-571](https://issues.folio.org/browse/UIQM-571)

UIQM-571  Added `marc-records-editor.item.put` to Derive Bib permission to fix issue with broken links after deriving a record.

---

CHANGELOG.md
package.json

Added `marc-records-editor.item.put` to Create Bib permission to fix issue with broken links after creating a record.
[UIQM-571](https://issues.folio.org/browse/UIQM-571)

UIQM-571  Added `marc-records-editor.item.put` to Create Bib permission to fix issue with broken links after creating a record.

---

CHANGELOG.md
package.json

Remove eslint deps that are already listed in eslint-config-stripes
[UIQM-543](https://issues.folio.org/browse/UIQM-543)

UIQM-543 Remove eslint deps that are already listed in eslint-config-stripes

---

src/QuickMarcEditor/utils.js

Wait for PUT request to finish after deriving before redirecting to Inventory
`onClose('id')` was added in https://github.com/folio-org/ui-quick-marc/pull/583, but now we're removing `shared` parameter in `onClose` in ui-inventory, so the issue is not reproduced
https://github.com/folio-org/ui-quick-marc/assets/19309423/b66b225f-0301-414f-bcf7-a887b9ddc419
[UIQM-571](https://issues.folio.org/browse/UIQM-571)

UIQM-571 Wait for PUT request to finish after deriving before redirecting to Inventory

---

CHANGELOG.md
src/QuickMarcEditor/utils.js
src/QuickMarcEditor/utils.test.js

Requirement Change: Allow user to Add/Edit 010 $a when linking is based on 001.
[UIQM-573](https://issues.folio.org/browse/UIQM-573)
https://github.com/folio-org/ui-quick-marc/assets/77053927/d9f46ca2-7fb9-4992-a126-a02b89f38137 …

UIQM-573: Edit MARC authority | Allow user to Add/Edit 010 $a when linking is based on 001.

---

CHANGELOG.md
src/QuickMarcEditor/QuickMarcEditorContainer.js

Don't load locations when MARC type is not Holdings.
[UIQM-591](https://issues.folio.org/browse/UIQM-591)

UIQM-591  Show permission `quickMARC: Create a new MARC authority record`. Don't load locations when MARC type is not Holdings.

---

CHANGELOG.md
src/QuickMarcEditor/constants.js
src/QuickMarcEditor/utils.js
src/QuickMarcEditor/utils.test.js

Remove fields that have no MARC tag and no subfield value.
https://github.com/folio-org/ui-quick-marc/assets/19309423/f9aa130c-8bc5-4ba6-86b6-16e15cd89324
[UIQM-534](https://issues.folio.org/browse/UIQM-534)

UIQM-534 Remove fields that have no MARC tag and no subfield value.

---

src/QuickMarcEditor/utils.js
src/QuickMarcEditor/utils.test.js

Delete saved fields that have empty tag and content
https://github.com/folio-org/ui-quick-marc/assets/19309423/4888e6ba-a46f-4270-89c8-07335abeea37
[UIQM-534](https://issues.folio.org/browse/UIQM-534)

UIQM-534 Delete saved fields that have empty tag and content (follow-up)

---

CHANGELOG.md
src/hooks/useAuthorityLinking/useAuthorityLinking.js
src/hooks/useAuthorityLinking/useAuthorityLinking.test.js

During linking, take the authority subfields first and then the bib subfields.
[UIQM-595](https://issues.folio.org/browse/UIQM-595)
https://github.com/folio-org/ui-quick-marc/assets/77053927/864286d7-60c8-4c78-863e-cb420f6e91f0 …

UIQM-595: During linking, take the authority subfields first and then the bib subfields.

---

CHANGELOG.md
src/queries/useMarcRecordMutation/useMarcRecordMutation.js
src/queries/useMarcRecordMutation/useMarcRecordMutation.test.js

By default, `useMutation` catches an error from `ky` which has format `{ response: { ... } }`. But quickMARC error parsing code needs the `response` object.
The fix is to override default error handling and throw `error.response` instead
https://github.com/folio-org/ui-quick-marc/assets/19309423/e89c5671-9cb1-47a1-b4f8-575c307276f2
[UIQM-596](https://issues.folio.org/browse/UIQM-596)

UIQM-596 Fix http error handling when Editing/Creating/Deriving MARC records.

---

CHANGELOG.md
src/QuickMarcEditor/SourceFileLookup/SourceFileLookup.js
src/QuickMarcEditor/SourceFileLookup/SourceFileLookup.test.js
src/hooks/useAuthorityLinking/useAuthorityLinking.js
src/queries/useAuthoritySourceFiles/useAuthoritySourceFiles.js
src/queries/useAuthoritySourceFiles/useAuthoritySourceFiles.test.js

Pass `selectable` as a search parameter to source files call
Fetch source files for linking from current tenant because the data is now propagated from central to member tenants
https://github.com/folio-org/ui-quick-marc/assets/19309423/bb0dc524-0f50-4fcf-a4c4-30aaeb30d2f2
[UIQM-606](https://issues.folio.org/browse/UIQM-606)

UIQM-606 Fetch only selectable source files for source file lookup modal.

---

CHANGELOG.md
src/hooks/useValidation/rules.js
src/hooks/useValidation/useValidation.test.js

- Added common rules to create authority records ruleset
- Updated tests to also test Create and Derive actions.
Many rules are the same for different quick marc action types (create/edit/derive), but initially tests only checked with edit.
To test all actions I added functions like `testBaseBibValidation` that return `describe` statements. This allow us to test the same cases with the same data, but 1 different parameter - quick marc action
https://github.com/folio-org/ui-quick-marc/assets/19309423/a6e78107-d3b2-41b4-8b6e-a363aa34f7d3
[UIQM-620](https://issues.folio.org/browse/UIQM-620)

UIQM-620 Added common validation rules for creating authority records

---

CHANGELOG.md
src/QuickMarcEditor/QuickMarcEditorRows/LinkButton/LinkButton.js
src/QuickMarcEditor/QuickMarcEditorRows/LinkButton/LinkButton.test.js

`useOkapiKy` uses `??` operator instead of `||`, so an empty value needs to be null for default tenant id to be applied
https://github.com/folio-org/ui-quick-marc/assets/19309423/a0cf8fcc-6cfd-4815-b480-903b4f8f1d9b
[UIQM-625](https://folio-org.atlassian.net/browse/UIQM-625)

UIQM-625 Use `null` instead of empty string as an empty tenantId value.

---

package.json

Whoops, missed this in #613. 
Refs [UIQM-637](https://folio-org.atlassian.net/browse/UIQM-637)

UIQM-637 use compatible @folio/plugin-find-authority

---

CHANGELOG.md
src/QuickMarcEditor/QuickMarcEditorRows/LinkButton/LinkButton.js
src/QuickMarcEditor/QuickMarcEditorRows/LinkButton/LinkButton.test.js

Use the `$` sign instead of `{dollar}` for search input and search query during manual linking.
[UIQM-639](https://folio-org.atlassian.net/browse/UIQM-639)
https://github.com/folio-org/ui-quick-marc/assets/77053927/c93d1692-d454-4353-8b89-0ed2ed6aa200 …

UIQM-639: Use the '$' sign instead of '{dollar}' for search input and search query during manual linking.

---

CHANGELOG.md
src/hooks/useValidation/rules.js
src/hooks/useValidation/useValidation.test.js

Added validation rule to prevent deletion of 010 when it is a linking point.
https://github.com/folio-org/ui-quick-marc/assets/19309423/355b59dd-9790-47ef-806f-66d19781b794
https://github.com/folio-org/ui-quick-marc/assets/19309423/bdbdaa79-3b37-490f-828f-66996818fa5c
[UIQM-649](https://folio-org.atlassian.net/browse/UIQM-649)

UIQM-649 Added validation rule to prevent deletion of 010 when it is a linking point.

---

src/QuickMarcEditor/QuickMarcEditor.js
src/QuickMarcEditor/utils.js
src/QuickMarcEditor/utils.test.js
src/hooks/useValidation/rules.js
src/hooks/useValidation/useValidation.test.js

Allow users to delete 010 fields when Authority record is not linked
https://github.com/folio-org/ui-quick-marc/assets/19309423/3f4b6f9c-7ab6-49ff-9975-9fa047bac7d0
[UIQM-649](https://folio-org.atlassian.net/browse/UIQM-649)

UIQM-649 Allow users to delete 010 fields when Authority record is not linked (follow-up)

---

CHANGELOG.md
package.json
src/QuickMarcEditor/QuickMarcEditorRows/LinkButton/LinkButton.test.js
src/QuickMarcEditor/QuickMarcEditorRows/QuickMarcEditorRows.js
src/QuickMarcEditor/QuickMarcEditorRows/SearchLink/SearchLink.js
src/QuickMarcEditor/QuickMarcEditorRows/SearchLink/SearchLink.test.js
src/QuickMarcEditor/QuickMarcEditorRows/SearchLink/index.js
test/jest/__mock__/stripesInventoryComponents.mock.js

Added `stripes-inventory-components` to peerDeps.
Added inventory search link next to 010 fields. The link will open Inventory app in a new tab with advanced search by lccn with `010 $a/$z` as values
https://github.com/folio-org/ui-quick-marc/assets/19309423/ca339f63-6676-4a62-a3aa-98279423b95a
[UIQM-660](https://folio-org.atlassian.net/browse/UIQM-660)
https://github.com/folio-org/ui-inventory/pull/2484
https://github.com/folio-org/stripes-inventory-components/pull/37

UIQM-660 *BREAKING* Added `stripes-inventory-components` to peerDeps. Added inventory search link next to 010 fields.

---

src/QuickMarcEditor/QuickMarcEditorRows/utils.js

Add button should also be disabled when creating/deriving holdings and authorities records
[UIQM-671](https://folio-org.atlassian.net/browse/UIQM-671)

UIQM-671 disable adding fields after 999ff when deriving/creating holdings and authorities (follow-up)

---

CHANGELOG.md
src/QuickMarcEditor/constants.js
src/QuickMarcEditor/utils.js
src/QuickMarcEditor/utils.test.js

When deriving a MARC Bib record 010 field content should be cleared
https://github.com/folio-org/ui-quick-marc/assets/19309423/51569036-dd60-49b3-8acb-1e33542aeb9e
[UIQM-661](https://folio-org.atlassian.net/browse/UIQM-661)

UIQM-661 Derive a new MARC bib record > Do not copy over 010 field values.

---

CHANGELOG.md
src/QuickMarcEditor/constants.js
src/QuickMarcEditor/utils.test.js

Fields 002, 004, 009 of the bib/authority record and fields 002, 009 of the holdings record are allowed to be saved without subfields.
[UIQM-670](https://folio-org.atlassian.net/browse/UIQM-670)
https://github.com/user-attachments/assets/4a3ae397-74ec-440d-9c56-9af7af119868
Ideally all of the PRs involved in breaking changes would be merged in the same day …

UIQM-670: Allow saving local control fields without subfield.

---

CHANGELOG.md
src/QuickMarcEditor/QuickMarcEditor.css
src/QuickMarcEditor/QuickMarcEditor.js
src/QuickMarcEditor/QuickMarcEditor.test.js
src/QuickMarcEditor/constants.js
src/hooks/useLccnDuplicationCheck/useLccnDuplicationCheck.js
src/hooks/useLccnDuplicationCheck/useLccnDuplicationCheck.test.js
src/hooks/useValidation/useValidation.js
translations/ui-quick-marc/en.json

Display a modal window if backend validation takes over 2s. Hide it once the validation is over.
To manage that modal the `manageBackendValidationModal` function is created with `setTimeout`.
[UIQM-632](https://folio-org.atlassian.net/browse/UIQM-632)
https://github.com/user-attachments/assets/e606d0a6-d4f2-4627-bf73-d7a72248c42c
Ideally all of the PRs …

UIQM-632: Run timer on submit during backend validation, if it takes over 2s, show modal.

---

src/hooks/useLccnDuplicationCheck/useLccnDuplicationCheck.js
src/hooks/useLccnDuplicationCheck/useLccnDuplicationCheck.test.js

Avoid showing an inline LCCN error message during the LCCN validation when 010 $a is empty.
Add existance check for 010 $a value to prevent LCCN check with empty $a.
[UIQM-658](https://folio-org.atlassian.net/browse/UIQM-658)
https://github.com/user-attachments/assets/cf90e381-6a30-47b6-8c14-253fd121fcf5
Ideally all of the PRs involved in breaking changes …

UIQM-658: Add existance check for 010 $a to prevent LCCN check with empty $a (follow-up).

---

src/queries/useLccnDuplicateConfig/useLccnDuplicateConfig.js

`/settings/entries` accepts a `query` paremeter with `scope` and `key` values, but we send `scope` and `key` directly
https://s3.amazonaws.com/foliodocs/api/mod-settings/settings.html#operation/getSettings
[UIQM-658](https://folio-org.atlassian.net/browse/UIQM-658)

UIQM-658 Fix format of parameters for getting /settings/entries (follow-up)

---

src/hooks/useValidation/rules.js
src/hooks/useValidation/useValidation.test.js
src/hooks/useValidation/validators.js

Added 001 validation rule for Create Authority. Will show an error message when an Authority Source file is not selected
https://github.com/user-attachments/assets/ea9bf169-6bc0-41a8-b590-c82ae60b5ffb
[UIQM-681](https://folio-org.atlassian.net/browse/UIQM-681)

UIQM-681 Added 001 validation rule for Create Authority (follow-up)

---

src/QuickMarcEditor/QuickMarcEditorContainer.test.js

Some tests started failing due to some changes in field names. Probably some dependency changed and now field names are composite - contain more than one label.
The tests can be fixed by using a regex for name matching

Fix field by name selectors

---

CHANGELOG.md
src/QuickMarcEditor/utils.js
src/QuickMarcEditor/utils.test.js
src/hooks/useAuthorityLinking/useAuthorityLinking.js
src/hooks/useAuthorityLinking/useAuthorityLinking.test.js

Fix an error when autolinking. Convert Leader from Object to string when fetching links autosuggestions.
https://github.com/user-attachments/assets/a50dac0b-7683-4296-929d-c6aee75fe711
[UIQM-688](https://folio-org.atlassian.net/browse/UIQM-688)

UIQM-688 Convert Leader from Object to string when fetching links autosuggestions.

---

CHANGELOG.md
src/QuickMarcEditor/QuickMarcEditor.js
src/QuickMarcEditor/QuickMarcEditor.test.js
src/QuickMarcEditor/QuickMarcEditorRows/QuickMarcEditorRows.js
src/QuickMarcEditor/QuickMarcEditorRows/utils.js
src/QuickMarcEditor/QuickMarcEditorRows/utils.test.js

Validation warnings should make fields have warning style
https://github.com/user-attachments/assets/ebe8422c-8c0e-437f-bd8d-c1c108639881
[UIQM-691](https://folio-org.atlassian.net/browse/UIQM-691)

UIQM-691 Show correct field and toast color when validation returns warnings.

---

CHANGELOG.md
src/QuickMarcEditor/QuickMarcEditor.js
src/QuickMarcEditor/utils.js
src/QuickMarcEditor/utils.test.js

Problem detected only on windows with polish programmer keyboard installed (default for polish).
No issue detected on Mac or Linux.
Prevent execute action for ex. "Save record" triggered from shortcut ctrl + s when inputing polish special chars ś or Ś. 
Detects pressing the ctrl and alt keys  and interrupts shortcut actions.
[UIQM-592](https://folio-org.atlassian.net/browse/UIQM-592)
Before changes 
https://github.com/user-attachments/assets/1370c99f-a16f-4775-ab85-95634ba78c97
After changes 
https://github.com/user-attachments/assets/19583e64-9dc7-428d-85c7-6ba4da8b517a

UIQM-592 Fix input polish chars into fields

---

CHANGELOG.md
package.json

Do not display the UI permission - Edit, View: Enable duplicate LCCN (010 $a) checking of MARC bibliographic and authority records
[UIQM-693](https://folio-org.atlassian.net/browse/UIQM-693)
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if …

UIQM-693: Hide permission - Edit, View: Enable duplicate LCCN (010 $a) checking of MARC bibliographic and authority records.

---

CHANGELOG.md
src/QuickMarcEditor/QuickMarcEditorRows/LinkButton/LinkButton.test.js
src/QuickMarcEditor/SourceFileLookup/SourceFileLookupModal.test.js
test/jest/__mock__/index.js
test/jest/__mock__/stripesComponents.mock.js
translations/ui-quick-marc/en.json

Remove the extra `$` sign in error messages.
[UIQM-695](https://folio-org.atlassian.net/browse/UIQM-695) …

UIQM-695: Remove extra `$` from error messages when adding/removing $t from 1XX of linked MARC authority record.

---

src/QuickMarcEditor/QuickMarcDeriveWrapper.js

use member tenant id for validation when deriving a bib record
[UIQM-699](https://folio-org.atlassian.net/browse/UIQM-699)

UIQM-699 use member tenant id for validation when deriving a bib record (follow-up)

---

CHANGELOG.md
src/QuickMarcEditor/QuickMarcEditorRows/QuickMarcEditorRows.js
src/QuickMarcEditor/utils.js
src/QuickMarcEditor/utils.test.js
src/hooks/useValidation/rules.js
src/hooks/useValidation/useValidation.js
src/hooks/useValidation/useValidation.test.js
src/hooks/useValidation/validators.js
translations/ui-quick-marc/en.json

Validate 006/007 field lengths.
https://github.com/user-attachments/assets/d347a458-b77c-4e0a-a22c-bb34e5f974d8
[UIQM-698](https://folio-org.atlassian.net/browse/UIQM-698)

UIQM-698 Validate 006/007 field lengths.

---

CHANGELOG.md
src/QuickMarcEditor/QuickMarcEditorRows/PhysDescriptionField/MicroformDescriptionFieldConfig.js

Change 007 Microforms type to allow 4 characters in RRR/RR field.
https://github.com/user-attachments/assets/c0104045-d6b6-49c8-ac81-c708d0c0c5b4
[UIQM-708](https://folio-org.atlassian.net/browse/UIQM-708)

UIQM-708 Change 007 Microforms type to allow 4 characters in RRR/RR field.

---

.github/workflows/build-npm-release.yml
.github/workflows/build-npm.yml
CHANGELOG.md
src/MarcRoute/MarcRoute.js
src/MarcRoute/MarcRoute.test.js
src/QuickMarcEditor/QuickMarcEditor.test.js
src/QuickMarcEditor/QuickMarcEditorContainer.test.js
src/queries/useUserTenantPermissions/useUserTenantPermissions.js
src/queries/useUserTenantPermissions/useUserTenantPermissions.test.js

Be able to edit MARC bibliographic record in the member tenant having required permissions in the sub-permissions.
Add also sub-permissions to the set of permissions returned by `useUserTenantPermissions`.
[UIQM-735](https://folio-org.atlassian.net/browse/UIQM-735)
https://github.com/user-attachments/assets/b8dd1d9b-8904-4e90-8129-43cc61334b85
Ideally all …

UIQM-735: Return also sub permissions in `useUserTenantPermissions` hook.

---

translations/ui-quick-marc/en.json

Fix a translation typo
[UIQM-730](https://folio-org.atlassian.net/browse/UIQM-730)

UIQM-730 fix translation typo (follow-up)

---

CHANGELOG.md
src/QuickMarcEditor/QuickMarcEditor.js
src/QuickMarcEditor/QuickMarcEditor.test.js

Don't show warn/fail error toasts when there are no warns/fails.
https://github.com/user-attachments/assets/7b50e81e-23ba-4b43-b3fd-e0d80819a114
[UIQM-740](https://folio-org.atlassian.net/browse/UIQM-740)

UIQM-740 Don't show warn/fail error toasts when there are no warns/fails.

---

CHANGELOG.md
src/QuickMarcEditor/QuickMarcEditor.js
src/QuickMarcEditor/QuickMarcEditor.test.js

When a user chooses "Cancel" option on any of the confirmation modals they should have focus on the last focused element before the modal opened.
https://github.com/user-attachments/assets/3cf9f4ca-9485-4e10-9bf2-681a97c68f6c
[UIQM-728](https://folio-org.atlassian.net/browse/UIQM-728)

UIQM-728 Keep focus on last focused element when user cancels on confirmation modals.

---

CHANGELOG.md
package.json

Reverts folio-org/ui-quick-marc#785
We no longer support invisible permissions in Eureka, so the previous PR is no longer valid and should be reverted.

Revert " [UIQM-763] Enable settings menu by default"

---

CHANGELOG.md
src/QuickMarcEditor/useSaveRecord/useSaveRecord.test.js
src/QuickMarcEditor/useSaveRecord/useSubmitRecord/useSumbitRecord.js

When a user creates a new record in a central tenant and clicks "Save and keep editing" the pane title should say "Edit shared...".
Add `shared=true` parameter to url when a user saves and keeps editing a Bib/Authority record on a central tenant. This parameter tells quickMARC that we're editing a shared record.
Central tenant
https://github.com/user-attachments/assets/e607a943-adbc-4dda-abac-ec246df5a6c3
Member tenant
https://github.com/user-attachments/assets/518c6500-bb38-405c-9eea-26d3f7b5c158
[UIQM-765](https://folio-org.atlassian.net/browse/UIQM-765)

UIQM-765 Add `shared=true` parameter to url when a user saves and keeps editing a Bib/Authority record on a central tenant.

---

CHANGELOG.md
src/QuickMarcEditor/useSaveRecord/useSaveRecord.js
src/QuickMarcEditor/useSaveRecord/useSaveRecord.test.js

Currently, when a _member_ tenant _derives_ a _shared_ record the validation endpoint uses the central tenant id, which is incorrect since the record will become local, local records should use validation rules specified for the member tenant. 
After this PR is merged the validation will not use the central tenant id when deriving a shared record in a member tenant. 
The `isRequestToCentralTenantFromMember` checks if the record is shared and bib/authority and if the user is in the member tenant, it remains only to exclude the deriving action (`action !== QUICK_MARC_ACTIONS.DERIVE`).
[UIQM-766](https://folio-org.atlassian.net/browse/UIQM-766)
https://github.com/user-attachments/assets/7bb422b8-5211-4b6b-a5b1-bd73fb411f90
Before merging this PR, please go through the following list and take …

UIQM-766: useSaveRecord - do not use central tenant id when deriving a shared record from a member tenant.

---

CHANGELOG.md
src/QuickMarcEditor/QuickMarcEditorContainer.js

Users should be able to create MARC Holdings records in shared Instance records from a member tenant.
[UIQM-771](https://folio-org.atlassian.net/browse/UIQM-771)

UIQM-771 FE | Support Create/Update action for MARC holdings record on shared Instance from member tenant on ECS environment

---

CHANGELOG.md
src/QuickMarcEditor/QuickMarcEditorRows/LinkButton/LinkButton.js

When linking an Authority to a shared MARC Bib record - fetch linking rules from the central tenant
[UIQM-773](https://folio-org.atlassian.net/browse/UIQM-773)

UIQM-773 Use Central tenant linking rules when user editing Shared MARC bib from Central or Member tenant

---

src/QuickMarcEditor/QuickMarcEditorRows/LinkButton/LinkButton.js

Fetch linking rules from central tenant only when editing a shared MARC Bib record.
When deriving a shared MARC Bib record or creating a new MARC Bib record we should fetch linking rules from a current member tenant, because a created record will be a local MARC Bib record.
[UIQM-773](https://folio-org.atlassian.net/browse/UIQM-773)

UIQM-773 use member tenant linking rules when deriving a shared bib record (follow-up)

---

src/QuickMarcEditor/QuickMarcEditorRows/LinkButton/LinkButton.js

Only 6XX, 7XX and 8XX fields that should be browsed by Name-title are 600, 610, 611, 700, 710, 711, 800, 810, 811
[UIQM-785](https://folio-org.atlassian.net/browse/UIQM-785)

UIQM-785 only browse by name-title for 600, 610, 611, 700, 710, 711, 800, 810, 811 tags
